### ISSUE TITLE
Error when creating internal orders

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#3649] opened 2024-04-22 00:01 UTC
## What went wrong? 😲
 
If you try to create an internal order you get this:

<img width="1227" alt="Screenshot 2024-04-22 at 11 54 21 AM" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/0e4dfc04-2390-4f5d-8be8-f37eed9909d5">

The problem is that in #3396 this

```
    onSuccess: ({ requisitionNumber }) => {
```

was changed to this:

```
}).then(requisitionNumber => {
```

so the object is returned, rather than destructuring the result.

## Expected behaviour 🤔
Should redirect without error

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'Internal orders'
2. Click on 'New order'
3. See error

## Your environment 🌱

- Open mSupply Version: 2.0.0 RC

**Comment by roxy-dao** [comment] 2024-04-22 00:20
Duplicate of #3534

**Closed by roxy-dao** 2024-04-22 00:20 UTC
Labels: bug, Severity: High
