### ISSUE TITLE
Report translation

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#4672] opened 2024-08-22 21:10 UTC
## Is your feature request related to a problem? Please describe 👀

Reports are configured with translations, allowing for translations to happen automagically and reduce the need to duplicate report.

## Describe the solution you'd like 🎁

* Re-use existing translation strings defined for front end
* Make sure there is a fall back translation in tera
* Translate based on users current language (fall back to english)
* Document process when translations are changed to update reports (will require versioning ?)
* Usually we would need to build bundle to have it available in embedded rust, for ease of dev work may need to switch to translations in src rather then dist folder in dev mode
* May require new report localisation (for new string that are report specific)
* Check if there are differences in HSH, especially with the translation caching

### Describe alternatives you've considered 💭

Briefly thought about another set of translations specific to reports. We already have infrastructure for translations, including translation server and also have quite a few existing translations.

**Comment by mark-prins** [comment] 2024-08-29 04:28
Given that reports are stored and delivered outside of the codebase there's a disconnect between reports and translations. we could validate existing reports when upgrading thought i don't feel it's necessary. perhaps require fallbacks in reports, in case the translation doesn't exist? that doesn't account for changes in the translations though, the key may exist but not be suitable.

Raising as a concern and is something to consider when implementing.

**Comment by mark-prins** [comment] 2024-09-08 23:46
There's some duplication with #4682 - perhaps this can be closed in favour of the epic if the versioning requirement is captured somewhere

**Comment by jmbrunskill** [comment] 2024-09-13 06:02
@fergie-nz Can we close this now?

**Comment by fergie-nz** [comment] 2024-09-15 21:10
Closing as duplicate of #4682

**Closed by fergie-nz** 2024-09-15 21:10 UTC
Labels: enhancement, feature: reports

**Comment by marthakeezy** [comment] 2024-10-01 05:02
Anusha is smashing it in #4899, moving to Done ✅
