### ISSUE TITLE
Server running and test errors from trying to JSON parse index.ts file

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#5026] opened 2024-10-07 19:58 UTC
## What went wrong? 😲

Error (non breaking) from trying to parse index file in server tests:

```
[2024-10-07T19:50:53Z ERROR service::localisations] Failed to parse JSON file "index.ts": Error("expected value", line: 1, column: 1)
[2024-10-07T19:50:53Z ERROR service::localisations] Failed to parse JSON file "index.ts": Error("expected value", line: 1, column: 1)
[2024-10-07T19:50:53Z ERROR service::localisations] Failed to parse JSON file "index.ts": Error("expected value", line: 1, column: 1)
[2024-10-07T19:50:53Z ERROR service::localisations] Failed to parse JSON file "index.ts": Error("expected value", line: 1, column: 1)
```

## Expected behaviour 🤔

Filter out the index.ts from read json files.
Maybe something like:
```
.filter(|name| name != "./reports/index.ts")
```
as per server/cli/src/cli.rs

## How to Reproduce 🔨

Run cargo test

## Your environment 🌱

- Open mSupply Version: develop

**Comment by jmbrunskill** [comment] 2024-10-07 20:27
Duplicate of https://github.com/msupply-foundation/open-msupply/issues/4856

**Comment by jmbrunskill** [comment] 2024-10-07 20:28
@fergie-nz I think it's better to just filter for `.json` files, since that's what we're trying to find...

**Comment by jmbrunskill** [comment] 2024-10-07 20:28
dup

**Closed by jmbrunskill** 2024-10-07 20:28 UTC
Labels: bug, needs triage, needs daily triage
