### ISSUE TITLE
The filter options wont populate if the first characters of the filter options is selected

### ISSUE THREAD

**Issue by santoshkhanal12** [msupply-foundation/open-msupply#2788] opened 2024-01-22 07:27 UTC
## What went wrong? 😲

The filter options wont populate if the first characters of the filter options is selected

## Expected behaviour 🤔

No Other window should open up, when selecting the chracters in filter, and when correct key is pressed it should select correct filter option.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Open mSupply
2.Open any filter (Patients, locations, stocktakes and others )
3. Click on filter options box
4. You will see List of options of filter
5. Click on the first chacters of the filter
6. The filter option won't get selected (BUG)

![Screenshot 2024-01-22 at 16 59 04](https://github.com/msupply-foundation/open-msupply/assets/117138852/4fef15be-bbbc-435c-96bf-82a4e882173d)

As mentiond in docs: https://docs.msupply.foundation/docs/introduction/tutorial/ The window would react according to shortcut key. Not according to the chracters entered in the filter.

https://github.com/msupply-foundation/open-msupply/assets/117138852/9209239f-58ea-4902-9948-e10ab31deb1f

## Your environment 🌱

 - Version: 
 - Platform: 1.6.00
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [x] desktop (windows)
   - [ ] desktop (macOS)
   - [x] server (windows)

**Comment by roxy-dao** [comment] 2024-01-22 20:24
It works for me on desktop 🤔 and also tried on the demo site and works too... The video doesn't appear to be working for me 😭

**Comment by mark-prins** [comment] 2024-01-22 23:19
Hi @santoshkhanal12 - do you mean pressing the key on the keyboard?

This isn't expected behaviour if so - the global keyboard shortcuts apply (so, pressing `d` shows the dashboard) but there is no keyboard shortcut for the filter drop down.

**Comment by nisha-dangol** [comment] 2024-01-23 03:15
Hi @mark-prins @roxy-dao ! 
I think what he meant was that the shortcuts were retaining despite the selection of filter, which could be a bit confusing (and, yes for pressing the key on keyboard, for desktop users)! 
For example, in his screenshot of Patients filter, when we select Patients filter and it shows the dropdown (Date of birth, Gender...bla bla..), it is kinda normal to expect that D would select one of those dropdown options (in this case, Date-of-birth!), but instead it's throwing you to Dashboard screen (which is the current shortcut for Dashboards window).
So, the next question could be `Do we want to keep retaining shortcuts even at the time of filter selections?`

**Comment by santoshkhanal12** [comment] 2024-01-23 07:34
> Hi @santoshkhanal12 - do you mean pressing the key on the keyboard?
> 
> This isn't expected behaviour if so - the global keyboard shortcuts apply (so, pressing `d` shows the dashboard) but there is no keyboard shortcut for the filter drop down.

@mark-prins @roxy-dao @nisha-dangol I mean the filter should be working like this:

https://github.com/msupply-foundation/open-msupply/assets/117138852/b791dd2a-8da6-469d-95cf-664ecd4a39e2

**Comment by mark-prins** [comment] 2024-01-23 22:21
thanks - yes, that's what I thought you meant.
We didn't intend the filter list to be used that way, you have to click the item in the list. 
The filter component could be changed which would allow typing entries in - but that would cause a few problems. The input used in the Stocktakes example ( an autocomplete component ) lets the user type in anything. but the filter list is a specific list of filters that are available and the user needs to pick one. We'd also have to find a way to add the 'remove all filters' option even when the typed in letter doesn't match that name

As such - this isn't a bug, the filter list is working as intended. And I think the global keyboard shortcuts should still work, even when a drop down list is opened.

that said, I'm worried that people will find the behaviour strange like you have. 
Could we close the issue and reopen if we get feedback from users?

**Comment by mark-prins** [comment] 2024-01-31 22:56
Triage meeting: decided to close, the filter drop down list doesn't accept filtering in this way

**Closed by mark-prins** 2024-01-31 22:56 UTC
Labels: bug
