### ISSUE TITLE
Limit on number of backups

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#4696] opened 2024-08-27 06:14 UTC
## Is your feature request related to a problem? Please describe 👀

Should be able to specify limit on number of backups, through configuration file. This was requested after talking to support. Want to sneak into 2.2.1 to get deployed for current omSupply central server

**Comment by lache-melvin** [comment] 2024-08-27 21:36
Closed by #4697

**Closed by lache-melvin** 2024-08-27 21:36 UTC
Labels: enhancement, Severity: Hotfix

**Comment by AnushaUp** [comment] 2024-09-19 11:52
# 🧪 Testing

- [ ] Do a few backups.
- [ ] Set max_number_of_backups in configuration file to something low
- [ ] Do a few more backups and check that only specified number of backups remain (in chronological order)
- [ ] Make sure to check use case where max_number_of_backups is higher then current number of backups

**Comment by AnushaUp** [comment] 2024-11-05 12:07
> * Do a few more backups and check that only specified number of backups remain (in chronological order)

@andreievg what is the expected behaviour here? Here are more number of backup files then expected. 
![Screenshot 2024-11-05 at 5 51 59 pm](https://github.com/user-attachments/assets/b53de081-1928-41ec-ad83-2d99cd4c39da)

**Comment by lache-melvin** [comment] 2024-11-13 20:14
Sorry for a late response @AnushaUp - are you sure this is the right `oms backups` folder? I think the backups should each create a folder, rather than just one file...

I've just tried it myself and the deleting after the max number seems to be working for me - would you be able to try again?

**Comment by marthakeezy** [comment] 2025-04-04 01:44
Hey @AnushaUp I just checked with @kahn-msupply from support team and this is being implemented for OMS servers and working as expected :) I'll move to Done but feel free to move back if you are still testing! Just seeing the last comms were in November I thought I'd clear out some issues

**Comment by AnushaUp** [comment] 2025-04-07 03:48
Thanks @marthakeezy and @kahn-msupply 👍
