### ISSUE TITLE
Location name column too narrow

### ISSUE THREAD

**Issue by mark-prins** [msupply-foundation/open-msupply#4730] opened 2024-09-02 22:07 UTC
## What went wrong? 😲

The title doesn't show!

![telegram-cloud-photo-size-1-5093600165746551998-y](https://github.com/user-attachments/assets/6d39fcd6-8b5c-4bad-b970-4449a461c92e)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to the location list

## Your environment 🌱

- Open mSupply Version: 2.02.01
- Legacy mSupply Central Server Version:

- Platform:

- Database type:

**Comment by andreievg** [comment] 2024-09-05 00:36
@AnushaUp is it possible to run through all of the screens and check column width at some point in the next week or two ?

Would be great to try changing the length of the cell content (like in this case shorter location name)

**Comment by AnushaUp** [comment] 2024-09-05 12:24
@andreievg Sure, I will check and update the result. Thanks!

**Comment by andreievg** [comment] 2024-09-12 02:35
@AnushaUp how did you get on with testing the other columns ?

**Comment by AnushaUp** [comment] 2024-09-12 08:06
@andreievg Hi, Sorry for the late response. Here are few screenshot of the tables that have UI issues and some of the table like `View stock` the header data appears to be shrinking.
<img width="1262" alt="Screenshot 2024-09-12 at 1 45 38 pm" src="https://github.com/user-attachments/assets/65f95700-bfdb-4420-8ae6-e30ae21e647e">
<img width="1262" alt="Screenshot 2024-09-12 at 1 45 23 pm" src="https://github.com/user-attachments/assets/98658a31-8b65-4280-936b-9c297c2c13cf">
<img width="1259" alt="Screenshot 2024-09-12 at 1 45 08 pm" src="https://github.com/user-attachments/assets/09351068-e3f0-4860-833c-97e8e506d828">
<img width="1261" alt="Screenshot 2024-09-12 at 1 44 55 pm" src="https://github.com/user-attachments/assets/c6934df9-f685-45ce-a309-7901164d1111">
<img width="1260" alt="Screenshot 2024-09-12 at 1 44 44 pm" src="https://github.com/user-attachments/assets/1bc25848-edb6-4b0a-8d56-505dec03fdd4">
<img width="1261" alt="Screenshot 2024-09-12 at 1 44 30 pm" src="https://github.com/user-attachments/assets/e7e8312e-1174-4243-b978-07d325f56b29">
<img width="1255" alt="Screenshot 2024-09-12 at 1 44 12 pm" src="https://github.com/user-attachments/assets/5062bd0e-ba61-4e7e-b46a-faf796f61b43">

**Comment by andreievg** [comment] 2024-09-12 23:57
https://github.com/msupply-foundation/open-msupply/issues/3177 <- could be related

**Comment by mark-prins** [comment] 2024-10-13 21:41
Can we also have item code on the stock page please

**Comment by marthakeezy** [comment] 2024-10-14 21:28
#3425

**Comment by roxy-dao** [comment] 2024-10-22 21:30
Closing as duplicate of #3425

**Closed by roxy-dao** 2024-10-22 21:30 UTC
Labels: bug, Severity: Normal
