### ISSUE TITLE
Add 'OK', 'Back' or 'Exit' button to the Server Log window

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3478] opened 2024-03-28 02:58 UTC
## Is your feature request related to a problem? Please describe 👀

When using a tablet and navigating under Admin -> Android Settings -> Server Log, a window showing the latest server log pops up. However, on a tablet there is no way to navigate out of this window. Clicking outside of the window does not close it, and the only way to get out of it is by using the tablet's back button which takes you to another part of omSupply, not the Admin page. 

On Google Drive, I have uploaded what the Server log window looks like on Desktop -> there are a few options, including 'OK' which closes the window and allows you to browse further. 

Link to screenshots ->> https://drive.google.com/drive/folders/1MhNnrqYHKDrbJW2GA7p1fe7u66FMAhov?usp=drive_link

## Describe the solution you'd like 🎁

For the tablet, there should either be the same 'OK' button, allowing to browse the Admin area further, or a little 'x' in the top right corner which allows you to close the window. 'OK' button will probably be better for continuity and to match the design of the Desktop. 

## Agreed Solution

Make sure the same buttons in desktop are displayed/available for android.

### Additional context 💌

The back button going back to dashboard is a separate issue with android https://github.com/msupply-foundation/open-msupply/issues/3209

### Moneyworks Jobcode 🧰

N/A

**Comment by lache-melvin** [comment] 2024-08-27 21:51
Duplicate of #3417

**Closed by lache-melvin** 2024-08-27 21:51 UTC
Labels: enhancement, platform: android, Priority: Should have
