### ISSUE TITLE
Number input rounding 

### ISSUE THREAD

**Issue by roxy-dao** [msupply-foundation/open-msupply#5462] opened 2024-11-19 00:13 UTC
## What went wrong? 😲
Rounding going wrong...

https://github.com/user-attachments/assets/7e9e0514-21eb-4c44-954e-6ed6285ac9b8

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to a number input that has decimals
2. Type same number over and over again
3. See numbers bounce

## Your environment 🌱

- Open mSupply Version:
- Legacy mSupply Central Server Version: 2.4.0-RC1

- Platform:

- Database type:

**Comment by Chris-Petty** [comment] 2024-11-19 01:36
Lol amazing. Working around, prooobably can enter the number you want up to the dp allowed yea?

**Comment by lache-melvin** [comment] 2024-11-19 02:38
Closing as duplicate of #4213

**Closed by lache-melvin** 2024-11-19 02:38 UTC
Labels: bug, front-end, needs triage, Severity: Normal
