### ISSUE TITLE
CCEI: `Model` field appears to be editable, but it shouldn't be

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#4204] opened 2024-06-19 15:51 UTC
## What went wrong? 😲

The `Model` field in the CCEI module appears to be editable: 

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/b4874b41-d2a6-4505-adf7-b74142a4c29e)

## Expected behaviour 🤔

`Model` field is just a normal non-editable field like all the others

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version: 2.1.0

**Comment by lache-melvin** [comment] 2024-06-19 20:49
Looks like this was added intentionally here #4002 - investigating as to why... 😁

**Comment by lache-melvin** [comment] 2024-06-20 02:07
Conclusion: no one knows quite what it's doing there 🤷‍♀️  It might have had a purpose at some point, but we're not saving the edited value, so can back out for now and implement properly if the need arises!

**Comment by lache-melvin** [comment] 2024-06-20 21:00
Closed by #4210

**Closed by lache-melvin** 2024-06-20 21:00 UTC
Labels: bug, Team Piwakawaka, feature: CCEI

**Comment by marthakeezy** [comment] 2024-06-24 05:39
Tested in V2.1.0-RC2 (Central Server) - the issue is no longer there :) Moving to done as build test passed ✅
