### ISSUE TITLE
Unit price is `-$NaN.00` when you create outbound shipments by masterlist

### ISSUE THREAD

**Issue by santoshkhanal12** [msupply-foundation/open-msupply#3981] opened 2024-05-22 11:38 UTC
## What went wrong? 😲

Unit price is `-$NaN.00` when you create outbound shipments by masterlist

![Screenshot 2024-05-22 at 16 46 23](https://github.com/msupply-foundation/open-msupply/assets/117138852/62d22a8c-205b-4635-b0bf-58bc36677809)

## Expected behaviour 🤔

There should be numeric value like `0.00`

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Outbound Shipments
2. Create new outbound shipments 
3. Add items form the masterlist 
4. After the items are added see the Unit Price Column
5. The label `-$NaN.00` is seen(BUG)

## Your environment 🌱

- Open mSupply Version: v2-0-01
- Legacy mSupply Central Server Version: v7-15-dev12

- Platform: Server 

- Database type: Sqlite

**Comment by roxy-dao** [comment] 2024-05-22 19:56
Duplicate of #3968

**Comment by lache-melvin** [comment] 2024-05-22 22:06
Reopening as not fixed by #3975, this is for the display component rather than input.

**Comment by lache-melvin** [comment] 2024-05-23 00:24
Closed by #3990

**Closed by lache-melvin** 2024-05-23 00:24 UTC
Labels: bug, Team Ruru 🦉, Severity: Hotfix

**Comment by AnushaUp** [comment] 2024-05-23 09:17
# 🧪 Testing
Tested in oms apk `V2.0.02`


- [ ] Create outbound shipment
- [ ] Add lines from master list (so placeholder lines created)
- [ ] TEST: Unit price shows $0.00
