### ISSUE TITLE
Unable to add Date of Birth to an existing patient

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#4940] opened 2024-10-01 04:12 UTC
## What went wrong? 😲

When a patient is created without Date of Birth, and then edited later, Date of Birth is not saving. Getting the following error: 

<img width="1370" alt="Patient Age" src="https://github.com/user-attachments/assets/bed6a466-becf-44de-9067-ccace72fb053">

Everything else is saved with no issues

<img width="1281" alt="Saved" src="https://github.com/user-attachments/assets/d5bd1e70-7e88-443c-af85-5b1162106704">

## Expected behaviour 🤔

Should be able to edit Date of Birth after creation, and it should be saved with no issues

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Dispensary -> Patients
2. Create a new patient but leave Date of Birth blank
3. Save the patient -> navigate back to them
4. Try adding Date of Birth -> see error

## Your environment 🌱

- Open mSupply Version: V2.3.0-RC3
- Legacy mSupply Central Server Version: V7.17.10

- Platform: Tablet (apk)

- Database type: SQLite3

**Comment by lache-melvin** [comment] 2024-10-01 18:40
Closing as duplicate of #4912

**Closed** 2024-10-01 18:41 UTC
Labels: bug, needs triage, Severity: High, needs daily triage
