### ISSUE TITLE
Testing for v1.5

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#2448] opened 2023-11-07 05:35 UTC
# Testing for v1.5.00
Not a bug/issue; just to keep track of what has been tested/looked at so far! 
Please note that there is no standard test suite yet, so the testing is to be carried out with reference to [the omSupply docs! ](https://docs.msupply.foundation/docs/introduction/introduction/)

**Any suites/tests that has been tested is to be commented out.** 

## Let's try to aim:
- [ ] DISTRIBUTION
    - [ ] Customers
    - [ ] Requisitions
    - [ ] Outbound Shipments
- [ ] REPLENISHMENT
    - [ ] Suppliers
    - [ ] Internal Orders
    - [ ] Inbound Shipments
- [ ] CATALOGUE
    - [ ] Items
    - [ ] Master Lists
- [ ] INVENTORY
    - [ ] Locations
    - [ ] Stocktakes
    - [ ] Stock
- [ ] ADMINISTRATION
    - [ ] Display Settings
    - [ ] Synchronisation
    - [ ] Permissions    
- [ ] SYNCHRONISATION
    - [ ] Synchronisation
- [ ] COLD CHAIN
  - [ ] Monitoring: Chart
  - [ ] Monitoring: Breaches
  - [ ] Monitoring: Log
  - [ ] Sensors
  - [ ] Upload of fridge tag data
  - [ ] Cold chain application integration
  - [ ] Notifications

**Note**: Let's leave out the Dispensary, oms-programs and remote-authorisation for now!

**Comment by AnushaUp** [comment] 2023-11-07 11:01
Tested in omSupply `v1.5.00-RC1` with mSupply `V7-10-00-Beta9`
- [ ] DISTRIBUTION
    - [ ] Customers
    - [ ] Requisitions
    - [ ] Outbound Shipments

**Comment by mark-prins** [comment] 2023-11-07 19:51
Could you please include the cold chain work - for me, this is the most important to have tested as it is all the new work. We should not have affected existing functionality (much!) 
The problem is that there are no docs yet, I'll try and get those underway today.

- [ ] COLD CHAIN
  - [ ] Monitoring: Chart
  - [ ] Monitoring: Breaches
  - [ ] Monitoring: Log
  - [ ] Sensors
  - [ ] Upload of fridge tag data
  - [ ] Cold chain application integration
  - [ ] Notifications

**Comment by AnushaUp** [comment] 2023-11-08 09:41
@mark-prins hi, the test suit is updated and the setup is also done. Let us know if the documentation is available so that we can start.

**Comment by mark-prins** [comment] 2023-11-09 22:38
Thanks @AnushaUp!
The [cold chain documentation](https://docs.msupply.foundation/docs/coldchain/introduction/) is ready now 🙏

**Comment by AnushaUp** [comment] 2023-11-10 10:56
- [ ] REPLENISHMENT
    - [ ]  Suppliers
    - [ ]  Internal Orders
    - [ ]  Inbound Shipments

**Comment by mark-prins** [comment] 2023-11-14 03:35
- [ ] Outbound Shipments
  - [ ] Choose Distribution > Outbound Shipment in the navigation panel.
  - [ ] You will be presented with a list of Outbound Shipments (if you don't see any, you are probably just starting!).
  - [ ] View a list of Outbound Shipments
  - [ ] Create a new Outbound Shipment
  - [ ] Export Outbound Shipments to a .csv file
  - [ ] Print one or multiple Outbound Shipments
  - [ ] The list can display a fixed number of shipments per page. On the bottom left corner, you can see how many shipments are currently displayed on your screen.
  - [ ] If you have more shipments than the current limit, you can navigate to the other pages by tapping on the page number or using the right of left arrows (bottom right corner).
  - [ ] You can also select a different number of rows to show per page using the option at the bottom right of the page.
     ###   Search by Customer Name
  - [ ] You can filter the list of shipments by customer name. The filter should work properly.
  - [ ] Type the name of customer in the `search by name` field (on the left, just above the headers). All the shipments for this customer will appear in the list.
     ###  Exporting Outbound Shipments
  - [ ] The list of Outbound Shipments can be exported to a comma separated file (csv). Simply click the export button (on the right, at the top of the page)
  - [ ] The file will be downloaded right after that
  - [ ] This should download all the Outbound shipments, not just the current page
  - [ ] Shipments are exported using selected table in the table.
     ### Delete an Outbound Shipment
  - [ ] Select the shipment that you want to delete by checking the box on the left end of the list. You can select more than one shipment to be deleted. You can even select them all using the master checkbox in the list headers.
  - [ ] Open the Select dropdown (top right corner, above the list) and select Delete selected lines.
  - [ ] A notification confirms how many shipments were deleted (bottom left corner).
  - [ ] A notification confirms how many shipments were deleted(bottom left corner).
  - [ ] You can only delete outbound shipments with s status `NEW`
     ### Creating an Outbound Shipment
   - [ ] Press the `New Shipment` button, in the top right corner
   - [ ] A new window `Customers` opens, inviting you to select a customer.
   - [ ] There you will be presented with a list of available customers(which are visible in the list of customer of current store)
   - [ ] You can either select your customer from the list or you can type as much of a customer name
   - [ ] Once you press` Enter`, your Outbound Shipment is automatically created
   - [ ] If you have selected the wrong customer, you can change the customer name in the Customer Name field or select one the dropdown list.
   - [ ] Once your Outbound Shipment has been created, you can enter a customer reference in the Customer Ref field, if they have one (eg. PO#1234567)
      ### Additional Info
   - [ ] In the additional info section, you can see who created the Outbound Shipment (name of the user)
   - [ ] View and edit the Outbound Shipment color. Tap on the coloured circle and select a color from the pop-up
   - [ ] Write or edit a comment
      ### Related Documents
   - [ ] In the Related Documents section, you can see other related transaction document for the Outbound Shipment.
   - [ ] If your Outbound Shipment was created to fulfil a Requisition, the reference number of the requisition would appear in this section. In the future, other documents such as temperature records, transportation documents or pick slips will also be included.
       ### Invoice Details
   - [ ] In this section, you will see by default the total selling price of the items listed in the Outbound Shipment.
   - [ ] You can also add service charges by the following ways
       - [ ] Tap on the Edit Service Charges button. A new window opens.
       - [ ] Tap on the Add charge button on the new window. A new line appears in the list of charges. You tap on Cancel if you do not wish to add anything.
       - [ ] Name: Select a service charges in the dropdown list. You can customise the list of available charges. Contact your administrator
       - [ ] Comment: You can add a comment to provide further details about the new charge
       - [ ] Amount: Enter the amount of the charge
       - [ ] Tax: Enter a % of tax for the charge
       - [ ] Total: The total field is automatically calculated based on the Amount and the Tax percentage
       - [ ] Delete: You can tap on the Delete icon to delete the charge
     ### Transport Details
  - [ ] In this section, you can see or edit a transport reference number (eg. a booking or a tracking reference number)
- [ ] Outbound Shipment Status Sequence
- [ ] The status sequence is located at the bottom left corner of the Outbound Shipment screen.
- [ ] Passed statuses are hightlighted in blue, next statuses appear in grey.
- [ ] If you hover over the status sequence, a shipment history window appears. You can see the date when a shipment was updated from one status to another.
  ### Hold Checkbox
- [ ] Located on the buttom left corner, on the left of the status sequence
- [ ] Checking the `Hold` checkbox prevents the Outbound Shipment from being updated to the next status.
  ### Cancel and Confirm button
- [ ] Tap on the Cancel button to quit the Outbound Shipment view and return to the Outbound Shipments list.
- [ ] The Confirm button updates the status of a shipment. The status which you can confirm depends on the current status of the shipment and follows the sequence shown below.
![Screenshot 2023-11-09 at 3 54 32 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/f84b845a-a333-4c4b-8aa4-6d1f00b0d0e9)
- [ ] You don't have to update a shipment to the next status in the sequence. You can choose to skip some of them to go directly to `Confirm Shipped` for example.
- [ ] Adding lines to an Outbound Shipment
- [ ] Tap on the Add Item button (top right corner).
- [ ] A new Add Item window opens.
- [ ] Adding using a barcode scanner
- [ ] For another way to add items, if you are using the desktop client or android app, you can make use of barcode scanning to add items.
- [ ] Select an Item
- [ ] In the Add Item window, you can look up an item by:
      -    Reading through the list of available items
      -    or by typing some or all of the item name
      -    or by typing some or all of an item code
- [ ] Once your item is highlighted, tap on the name or press Enter.
- [ ] Once the information is selected you can see the following information
- [ ] In the headers: You can see Item code and name (eg. 030453 Amoxicillin 250 mg Tabs),the available stock quantity for this item(eg. 3527 units) and the item's unit (eg. Tab).

![Screenshot 2023-11-10 at 2 26 20 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/69e934ac-996c-4f48-9944-89acf06bf0eb)
- [ ] Issue [Quantity] of units in packs of [Pack Size]
- [ ] In the Issue Quantity field, you can enter the quantity that you want to issue to your customer.
- [ ] By default, you are invited to issue a quantity of units. However, you have the possibility to issue a quantity of packs instead by changing the value in the second dropdown (Pack Size).
- [ ] Default value is Any when you are issuing units.
![Screenshot 2023-11-10 at 2 27 39 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/89478b17-5643-4a7d-a929-875ab5f885d6)
- [ ] List of available batches
- [ ] You should see the following list of batch numbers that you have in store for this item
![Screenshot 2023-11-10 at 2 29 15 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/bce886b0-2bf8-4a45-a597-ed28dec424ff)
- [ ] There is also final row in the table which is a placeholder line, if the status of the Outbound Shipment is `NEW`. The pleceholder line is used when the quantity you are issuing higher then your available stock.

![Screenshot 2023-11-10 at 2 33 52 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/3b590a0c-b642-4e97-90ab-161b99225b7e)
- [ ] Issue a quantity of units
- [ ] By default, you are invited to issue a quantity of units, regardless of the pack size (number of units in a pack).
- [ ] When entering a number in the Issue field, the system automatically chooses the batch number(s) with the closest expiry date
- [ ] In this list, the batches which are available for selection are shown first and the batches which are not (on hold or no stock available) are shown below and in a grey font.
- [ ] Warnings
- [ ] You may see one or more warning messages on the screen:
![Screenshot 2023-11-10 at 2 41 59 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/1c6c4aa7-4761-476d-b10b-8bb5ee0be69f)
- [ ] The warning also may be shown to let you know that some stock lines are expired.
- [ ] Issue a quantity of packs
- [ ] You can decide to issue a quantity of packs. To do this, you can change the value in the `Pack Size` dropdown.
- [ ] When a pack size is selected, stock lines which have a different pack size from the one selected are not available for selection. 
- [ ] As such, those rows are listed lower down in the table and are shown in a grey font, in the same way as other unavailable rows.
- [ ] Manual Allocation
- [ ] Regardless if you chose to issue a quantity of units or packs, you can always manually change the quantity at the batch number level directly before pressing on OK.
- [ ] You simply have to enter or edit the quantity in the Packs Qty Issued column.
- [ ] The values in the Total row will be automatically have to be updated with the new quantity.
- [ ] Issuing when there is not enough stock (Placeholder Line)
- [ ] If the amount to be issued is greater than the total stock available from all of the available lines, then the quantity to be issued will automatically be placed in the placeholder field, at the bottom of the list of available batch numbers.
- [ ] Placeholder lines can be allocated later when new stock arrives. However, all shipment lines must be allocated before confirming the allocation.
- [ ] When you look at an Outbound Shipment, you can see if a shipment line has not been allocated or has been partially allocated when it is highlighted in blue.
- [ ] Confirm Item and Quantity
- [ ] When you are happy with the quantity, you can either press on `OK` , `OK & Next` and `Cancel` button.
- [ ] All the button should work properly
- [ ] Adding lines to an Outbound Shipment using a Master List
- [ ] Tap on the `Add from master list` button (top right corner).
- [ ] A new Master Lists window opens and this allows you to select the required master list. Simply click on one of the lists (if you have some available). 
- [ ] The lists shown are those which are visible to the customer of the shipment.
- [ ] Click `OK` and you will then have unallocated (placeholder) lines added to your shipment.
- [ ] You can see - all of the quantities are zero. You can follow the steps for editing these lines.
- [ ] You should be able to edit the lines by tapping on it.
- [ ] Edit a Shipment Line
- [ ] Open the Outbound Shipment you want to edit.
- [ ] Tap on the line you want to edit. An identical window to Add Item appears. At this stage, edit the main` Issue Quantity` field or change the number of packs value at the batch number level.
- [ ] When editing a shipment line, you cannot change the item. You would need to delete the shipment line and create a new one.
- [ ] Delete a shipment line
- [ ] Open the outbound Shipment you want to edit
- [ ] Select the line(s) you want to delete by checking the box(es) on the right of the list.
- [ ] Go to the `Actions` dropdown menu (top right corner, above the list)
- [ ] Select the action `Delete selected lines`

### Processing an Outbound Shipment
- [ ] Allocating an Outbound Shipment
- [ ] There are 2 main ways to allocate a shipment line:
- [ ] When adding items, the system will automatically assign stock to the new shipment line when you enter a quantity. If you don't have enough stock, the system will add placeholder lines (unallocated lines).
- [ ] Bulk action `Allocate placeholder lines`:
- [ ] Select the lines that you want to allocate by checking boxes on the right hand side of the list
- [ ] In the `Actions` dropdown menu, select`Allocate placeholder lines`. System will check if there is available stock for each selected line and allocate them using the First to Expire, First Out (FEFO) logic. A notification will let you know whether the operation is successful or not.
- [ ] Confirming an Outbound Shipment's allocation
- [ ] Once all your shipments lines have been allocated, you can confirm the allocation.
- [ ] Lines must be assigned with one or several batch numbers. You won't be able to confirm the allocation if your shipment contains lines without batch numbers assigned to it (placeholder lines).
- [ ] To confirm the allocation, press the `Confirm Allocated` button.
- [ ] Once the allocation is confirmed,Shipment status is ALLOCATED
- [ ] You are now invited to confirm the picking via the Confirm Picked button
- [ ] All the items and their quantities will be reserved, meaning that they are no longer available for allocation
- [ ] You can print a pick slip to be sent to your warehouse so they can start preparing the shipment
- [ ] Confirming Outbound Shipment picking
- [ ] Picking refers to the process where individual items are picked from a fulfilment facility (usually a warehouse or a pharmacy store).
- [ ] Once a shipment has been allocated, next step is to go get the items to prepare the actual shipment. To help with that, you are able to generate a pick slip document. A pick slip indicates:
- The items to be picked
- The quantity and batch numbers for each item
- If you managed your inventory with storage locations, where items are located
- [ ] Once all items are picked and packed. You can then confirm the picking of the shipment to indicate that it is ready to be dispatched.
- [ ] To confirm that a shipment has been picked, tap on the `Confirm Picked` button.
- [ ] Once picking is confirmed:
- [ ] Shipment status is now PICKED
- [ ] Goods are no longer able to be allocated to other shipments
- [ ] You are now invited to confirm the shipping via the Confirm Shipped button
- [ ] An Inbound Shipment has been generated and is now visible to your customer
- [ ] At this stage you must be able to shipment lines, to add items or to delete existing lines.
- [ ] Confirming the Outbound Shipment shipping
- [ ] This is the last step to issue stock. This is critical step because when goods are confirmed as shipped, tey are no longer a part of your inventory records
- [ ] To confirm an Outbound Shipment has been shipped, tap on the `Confirm Shipped` button
- [ ] Once the shipping has been confirmed
- [ ] Shipment status is now SHIPPED
- [ ] Goods are no longer part of your inventory
- [ ] You can no longer edit shipment lines
- [ ] You can no longer delete the shipment
- [ ] You can print a delivery note or an invoice
- [ ] Tracking Progress of Outbound Shipments
- [ ] If your customer is also using mSupply, you will be able to see when they'll receive your shipments.
- [ ] Status will be `DELIVERED` when goods are received when your customer confirmed that they received your goods
- [ ] status will become `VERIFIED` when shipment has been verified by your customer. Goods are now part of their inventory.
- [ ] Viewing an Outbound Shipment Shipment
- [ ] When viewing a specific shipment, you can view the batches on that shipment grouped by item or with each batch listed separately. To change the view mode, click the `Group by item` switch.
- [ ] When grouped by item, you can expand the item to see individual batches, or use the expand in the table header to expand all grouped rows. If you click on an item you will also see all selected batches.
- [ ] If you do not have enough room on your screen, or simply aren't interested in some of the columns shown, you have the option of hiding which columns are shown in this view.
- [ ] Click on the `Show / hide columns` button which is at the top right of the table. This gives a list of the columns available - you can check the columns you want to see. The options chosen are stored for the current browser, so next time you view an Outbound Shipment, you will see the selected columns only. If you have chosen which columns to show, then the button is shown in blue to remind you that there are more columns available.

**Comment by mark-prins** [comment] 2023-11-17 02:20
Have moved test script templates over to a [wiki](https://github.com/msupply-foundation/open-msupply/wiki/Test-scripts) - let's see if that's useful for storing these

**Closed by mark-prins** 2023-11-17 02:20 UTC
Labels: Testing
