### ISSUE TITLE
Merging two items appears to create a duplicate of kept item in master lists

### ISSUE THREAD

**Issue by Chris-Petty** [msupply-foundation/open-msupply#3306] opened 2024-03-15 04:00 UTC
## What went wrong? 😲

After merging an item into `Acetylsalicylic Acid 100mg tabs`, when I view masters lists on omSupply with the kept item it appears twice.

![image](https://github.com/msupply-foundation/open-msupply/assets/7684221/6f09e10d-a942-4979-89a2-ad70d014a685)

Similar to https://github.com/msupply-foundation/open-msupply/issues/3276, this is because the master_list_item_join that was to the old item still exists but it's item_link now points to the kept item.

## Expected behaviour 🤔

After 2 items are merged, the deleted item is no longer visible and the kept item appears once.

Solving this is likely easiest by deleting what is effectively a duplicate master_list_item_join

## How to Reproduce 🔨

1. Sync omSupply with a site
2. On primary server merge 2 items that are both on the same master list
3. Sync OMS, the kept item will appear twice.

## Your environment 🌱

- Version: 1.7 dev (~rc2)
- mSupply version: 7.13 dev

- Platform: mac firefox

- Database type: sqlite3

**Comment by clemens-msupply** [comment] 2024-03-19 01:42
I did the following:
- Choose item A
- Create a new item B that is a duplicate of item A
- I merged item A into item B (keep the new item B) 

Afterwards I got, these are the entries in the sync_buffer:

![image](https://github.com/msupply-foundation/open-msupply/assets/88299195/29e1e8dd-91ef-4584-8270-a054e22ac2b5)

The new item is not there and thus the merge fails! mSupply bug?

Interestingly, there is a "Delete" for master_list_line for the old entry!

**Comment by Chris-Petty** [comment] 2024-03-19 02:05
> I did the following:
> 
>     * Choose item A
> 
>     * Create a new item B that is a duplicate of item A
> 
>     * I merged item A into item B (keep the new item B)
> 
> 
> Afterwards I got, these new entries in the sync_buffer:
> 
> ![image](https://private-user-images.githubusercontent.com/88299195/313885419-29e1e8dd-91ef-4584-8270-a054e22ac2b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTM2MTIsIm5iZiI6MTcxMDgxMzMxMiwicGF0aCI6Ii84ODI5OTE5NS8zMTM4ODU0MTktMjllMWU4ZGQtOTFlZi00NTg0LTgyNzAtYTA1NGUyMmFjMmI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDAxNTUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhNmQ3MTcyM2Q5ODcyOWEwZTRmNzM1YTdhYjFiYWMxYWY5ZjJhYWExZjg4NjMyODA3OGZhODNhZTUzZjVkZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MsMs1gbhU3-m_9ioIP2EfOnCFkUOLtUjrDc3hRHMLkU)
> 
> The new item is not there and thus the merge fails! mSupply bug?
> 
> Interestingly, there is a "Delete" for master_list_line for the old entry!

Yea the change log sends deletes as central server truly hard deletes the "deleted" record. If quickly making and deleting an item on central server, OMS may only get a delete and have never made the "item" record nor a "item_link". Up to this moment in OMS the assumption was that it'd fail deleting every time because it'd break FK constraints, and we could ignore that. That said, maybe we can ignore the merge failing like this?

Likewise to avoid the issue raised here in OMS, OG deletes duplicate joins as part of the merge process to avoid things appearing twice in lists/ambiguity in visibility logic (what if one join says visible and the other says invisible? We keep it visible). (Bearing in mind that OG also has `item_store_join` along side `master_list_item_join`).

Sending deletes at all is unfortunately is working as intended on central server end. The postgres dashboard database relies on it for updates removing things such as items from master lists.

**Comment by clemens-msupply** [comment] 2024-03-19 02:15
Sorry the problem is that the new item "7A51FD..." is not pushed to omSupply. The deletes are fine.

**Closed** 2024-03-21 02:14 UTC
Labels: bug, feature: merging, Team Tauhou, Severity: High
