### ISSUE TITLE
iSC/Cold Chain: Equipment -> Log creates a long string going beyond the screen

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#4278] opened 2024-06-25 23:22 UTC
## What went wrong? 😲

Cold chain -> Equipment -> Log -> Details - whenever an asset is updated, the update is a long string that is hard to read and also goes beyond the screen. The user has to scroll for quite a long time to get to the end of the string. 

<img width="1512" alt="Screenshot 2024-06-26 at 11 20 50 AM" src="https://github.com/msupply-foundation/open-msupply/assets/153777484/ed08b40f-ed0d-4871-844a-26fc1d23fedf">

## Expected behaviour 🤔

I think the user-friendly solution would be to maybe create a link or a button to export the update if needed - I am not sure the whole string has to be shown straight away. Or maybe there can be a tooltip which the user can click and see the whole information? 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Cold chain -> Equipment
2. Create an asset and update it (e.g. change some details)
3. Go to Log -> Details 
4. See a long string after an update has been done

## Your environment 🌱

- Open mSupply Version: V2.1.0-RC3
- Legacy mSupply Central Server Version: V7.15.05

- Platform: Desktop App on Windows

- Database type: SQLite3

**Comment by andreievg** [comment] 2024-06-27 00:59
Triage, needs design, severity low thought, not likely that someone will be using that data atm

**Comment by roxy-dao** [comment] 2024-11-21 19:37
Closing as duplicate of #5425

**Closed by roxy-dao** 2024-11-21 19:37 UTC
Labels: bug, feature: coldchain, Severity: Low, needs design
