### ISSUE TITLE
Add cli commands to show and print reports for easy testing and future development

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#5093] opened 2024-10-13 19:42 UTC
## Is your feature request related to a problem? Please describe 👀

Part of https://github.com/msupply-foundation/open-msupply/issues/4668

## Describe the solution you'd like 🎁

Add cli commands and possibly also dummy data similar to bash scripts of show.sh, print.sh etc in the OMS reports repo.

This would help both testing and faster development of reports.

**Comment by roxy-dao** [comment] 2024-11-05 02:24
Duplicate of #4882

**Closed by roxy-dao** 2024-11-05 02:24 UTC
Labels: enhancement, Priority: Should have, feature: reports
