### ISSUE TITLE
DOB JsonForms component shows wrong age calculation in days

### ISSUE THREAD

**Issue by CarlosNZ** [msupply-foundation/open-msupply#5470] opened 2024-11-19 03:07 UTC
## What went wrong? 😲

The DOB component suffers from the same problem that was fixed in [this issue](https://github.com/msupply-foundation/open-msupply/pull/5276), namely -- it should be using a "naive date" for its age calculation, but the DOB component does not, so we get a discrepancy when the current timezone is in a different day to the current GMT time:

![Screenshot 2024-11-19 at 3 59 55 PM](https://github.com/user-attachments/assets/2898c72c-f260-491e-82d7-99a55274cdd7)

## Expected behaviour 🤔

Age should be "0 days" when DOB is today's date.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Make sure your system timezone is in a different day to GMT (in NZ, this will be until 1pm, otherwise you'll need to temporarily switch to a different timezone)
2. Go to a Patient details page.
3. Edit their date of birth to the current date. 
4. Note the "Age" shows "1 day" instead of "0 days". (Compare this with the Summary in the Toolbar -- requires PR https://github.com/msupply-foundation/open-msupply/pull/5436 to show age in days in Summary)

## Your environment 🌱

- Open mSupply Version: 2.4.0

**Comment by lache-melvin** [comment] 2024-11-20 22:00
Duplicate of #5438

**Closed by lache-melvin** 2024-11-20 22:00 UTC
Labels: bug, needs triage, Severity: Normal
