### ISSUE TITLE
Blue Encounter status does not get updated unless the page is refreshed

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5384] opened 2024-11-12 03:06 UTC
## What went wrong? 😲

Encounter status does not get updated unless the page is refreshed or navigated away from and back to

https://github.com/user-attachments/assets/18b24612-9b53-4278-ae8f-4744022e1de7

## Expected behaviour 🤔

Should update with the dropdown field updating

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Dispensary -> Encounters
2. Create a new encounter
3. In the top right corner, click on the dropdown field and change between Pending, Cancelled and Visited
4. See the blue status at the top does not update

## Your environment 🌱

- Open mSupply Version: V2.3.2
- Legacy mSupply Central Server Version: V7.17.11

- Platform: Google Chrome browser

- Database type: SQLite3

**Comment by roxy-dao** [comment] 2024-11-12 03:16
Duplicate of ##4819. What version are you testing with?

**Comment by marthakeezy** [comment] 2024-11-12 03:26
Ah yes, I am on 2.3.2! All good to close then 🙏🏼

**Closed** 2024-11-12 03:27 UTC
Labels: bug, needs triage, Severity: Low, needs daily triage
