### ISSUE TITLE
Add ability to go back to previous step in a modal (5h)

### ISSUE THREAD

**Issue by lache-melvin** [msupply-foundation/open-msupply#3192] opened 2024-03-05 21:13 UTC
## Is your feature request related to a problem? Please describe 👀

There's no way to go back to the previous step here 😢 (but I entered some batch info wrong and I really wanna go back)
![Image](https://github.com/msupply-foundation/open-msupply/assets/55115239/4b03ec77-f26b-4098-ba6c-2df9f98916e4)

## Describe the solution you'd like 🎁

The Modal component offers `cancel`, `ok` and `next` button options - perhaps we could add a `back` button for cases like this.

### Describe alternatives you've considered 💭

Could also add some kind of linking feature to the wizard steps, so you could click them to go back to previous steps?

**Comment by CarlosNZ** [comment] 2024-03-05 21:24
> Could also add some kind of linking feature to the wizard steps, so you could click them to go back to previous steps?

I'd be inclined to have both as options (linked steps and "Back" button) -- if you had a many-step stepper, being able to jump to a specific step would be good.

**Comment by richardmoizeau** [comment] 2024-03-21 00:40
In order to avoid having to many buttons at the bottom, we can also consider changing the button "Cancel" to "Back" when not on the first step. 

>I'd be inclined to have both as options (linked steps and "Back" button) -- if you had a many-step stepper, being able to jump to a specific step would be good.

And I agree with this. Both would be good. Also considering having a dedicated way of navigating thru the steps (designs to be confirmed by @anisha-msupply): 

![Screenshot 2024-03-21 at 1 38 33 PM](https://github.com/msupply-foundation/open-msupply/assets/74992958/04c2f9b2-34c4-4b07-ac71-ec8bf3e75fed)

**Comment by andreievg** [comment] 2024-03-21 03:16
For now, to minimise the amount of work that needs to be done to get to MVP.

When return is created from shipment (no item id):

on step 1

(cancel) (-> reasons)

on step 2

(back) (Ok)

When we open them modal from shipment (item id)

on step 1

(cancel) (-> reasons) (Ok & Next)  // Ok & Next greyed out)

on step 2

(back) (Ok) (Ok & Next) // Ok & Next not greyed out

The (Ok) (-> reasons) button may be jumpy (since they will be different size ?), i am ok with that for now so that we can finish of returns

@richardmoizeau 

I'll leave you to make the decision

**Comment by CarlosNZ** [comment] 2024-03-21 03:19
@andreievg Yup, basically agreed with that for the Returns buttons -- the only difference is to not have a "Cancel" button and use a "Close" icon for the modal.

**Comment by richardmoizeau** [comment] 2024-03-21 03:35
I agree with the solution described by @andreievg. 

> The (Ok) (-> reasons) button may be jumpy (since they will be different size ?), i am ok with that for now so that we can finish of returns

@CarlosNZ, should we try to have roughly the same fixed size for both button ?  (> Reason) & (OK) or at least centered on at the same spot so you don't have to move your pointer/finger to click on the "same" button.

**Comment by richardmoizeau** [comment] 2024-03-21 03:36
> @andreievg Yup, basically agreed with that for the Returns buttons -- the only difference is to not have a "Cancel" button and use a "Close" icon for the modal.

OK. 

@mark-prins, good to keep it consistent since a stepper is implemented for the CCEI work.

**Comment by CarlosNZ** [comment] 2024-03-21 03:38
> @CarlosNZ, should we try to have roughly the same fixed size for both button ? (> Reason) & (OK) or at least centered on at the same spot so you don't have to move your pointer/finger to click on the "same" button.

💯

**Comment by andreievg** [comment] 2024-03-21 03:38
@mark-prins @richardmoizeau do we need to consider making this new UI/UX pattern, to 'close' the modal rather then clicking the 'cancel' button ? Or is it one of for this view ?

**Comment by mark-prins** [comment] 2024-03-21 20:04
It should be consistent - so we make the change for all modals. That's a big change though, so outside the scope of this issue. I'd like to run it past Anisha first as well, to get her take before we progress.

**Comment by richardmoizeau** [comment] 2024-03-21 20:33
@anisha-msupply =)

**Comment by andreievg** [comment] 2024-03-21 20:56
Oki thanks @mark-prins, in that case is it ok for now to do 'cancel' and 'back' button (as the same button that changes function/name based on the step) ?

**Comment by mark-prins** [comment] 2024-03-21 21:03
I'd prefer to wait until we get an opinion on the universal approach - but yeah, if the change can't wait then add another button 🙏

**Comment by CarlosNZ** [comment] 2024-03-27 03:53
Closed by #3411

**Closed by CarlosNZ** 2024-03-27 03:53 UTC
Labels: enhancement, Team Ruru 🦉, feature: returns
