### ISSUE TITLE
Can we have the same view of program requisition for both desktop & android?

### ISSUE THREAD

**Issue by nishaDangol-Sussol** [msupply-foundation/open-msupply#3797] opened 2024-05-06 07:51 UTC
## What went wrong? 😲
 
In Android, in the program request-requisition (normal IO looks fine),  the `Reorder threshold MOS`, `Target MOS` & `Hide stock over minimum` all appear on the left-side which makes the item-lines view fall way down in the screen. 

## Expected behaviour 🤔
I think it'd be good to have those columns on the right-side like it is in the desktop

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Configure programs-requisitions setup
2. Create a IO
3. Choose the programs and all other required fields 
4. Notice when the IO is created.
Look at the program request-requisition created from desktop:
<img width="1491" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/00eab44d-633a-46f5-99df-784601dfff09">

V/S the program request-requisition created from Android apk
<img width="1365" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/59193490/c7e66b32-fa28-4940-960a-5241891e24fb">

## Your environment 🌱

- Open mSupply Version: v2.0.0-rc3 apk
- Legacy mSupply Central Server Version: v7-14-00

- Platform: apk

- Database type: sqlite

**Comment by Chris-Petty** [comment] 2024-05-06 23:30
Once the on screen keyboard for "Filter items" is up can you see anything?

**Comment by Chris-Petty** [comment] 2024-05-06 23:35
I think "bug" because of the unpleasant UX, but technically probably an enhancement as it's just the screen width rearrangement not a bug as such. A narrow window on desktop does similar - note the blue box warning about program requisition editability makes this significantly worse than a normal requisition.

**Comment by lache-melvin** [comment] 2024-08-23 03:14
Bumping this, this got raised during a deployment - their tablets could see about 1.5 lines at a time because the header takes up so much space 🙈 

Dev tool emulation for reference...

https://github.com/user-attachments/assets/8bbb76b0-caef-45b5-98e3-c775a52a9961

**Comment by Chris-Petty** [comment] 2024-08-26 03:29
Ew! I'd even make this high/hotfix priority if users are complaining and I don't think one can or should be expected to work around literally inaccessible UI!

**Comment by Chris-Petty** [comment] 2024-08-26 04:22
For the sake of direction... how about just some kind of button to collapse and hide the details section (maybe just show supplier name)? Or alternative, show the blue notice as a toast, that may allow the grid to rearrange more compactly.

Also noticing the nav bar items are starting to get cut off...

**Comment by andreievg** [comment] 2024-08-26 04:30
Agree with Hotfix, lets try for 2.2.1 ?

Laché says maybe flex can be improved (especially with the blue info box). Also she mentioned maybe we can some things to the info bar

> Also noticing the nav bar items are starting to get cut off...

Nav bar would be collapsed on mobile (Perhaps this should really happen with screen size, not just check in native code)

> For the sake of direction... how about just some kind of button to collapse and hide the details section (maybe just show supplier name)?

We already have the info panel (that comes in from the right, not sure if we need more ?). Although this panel does move the whole UI to the left ¯\_(ツ)_/¯ 

My suggestion @mark-prins to clarify + decide:

Vertical real-estate is limited with landscape mode, and I think the table is important bit of UI. Maybe we relocate most things to the more panel ? Also I think we might have excess vertical padding and even wrapping in the direction where real estate is limited, that can be reduced.

> Or alternative, show the blue notice as a toast, that may allow the grid to rearrange more compactly.

Yeah it takes a lot of space, if max/min mos not editable maybe should be in the info panel together with information box

**Comment by mark-prins** [comment] 2024-08-26 05:33
> Nav bar would be collapsed on mobile (Perhaps this should really happen with screen size, not just check in native code)

the nav bar collapses based on screen size. it retains the user selection though, so if the user has opened the left nav manually, it will be open.

> Or alternative, show the blue notice as a toast, that may allow the grid to rearrange more compactly

people missed it, as a toast. even as a big blue box people don't always read / notice it.

I'm keen to move most of that toolbar guff into the more info panel. We do need clear affordance though. there's a lot of useful info and the configuration properties, and the first time that people reach this page they won't know that they exist.

Ideally we'd have something like a 'first user' notification- perhaps we could explore that as part of this issue? I'll talk to Mariya re that one.

Re the blue box notification - I would keep it where it is, but add the option to dismiss it. Should that be a permanent dismissal though? Unsure, but I think not.

**Comment by mark-prins** [comment] 2024-08-26 05:51
an example framework would be [react-interactive-tutorials](https://github.com/uptick/react-interactive-tutorials?tab=readme-ov-file)

**Comment by mark-prins** [comment] 2024-08-26 22:57
Some decisions!

* Keep `Supplier name` and `Reference` in-page
* Move the `Hide stock over minimum` to be vertically in-line with the filter (as this is a visual display control too)
* ( you could try and lift that line up a little, as per the screenshot below, to gain some more space )
* Move `reorder threshold MOS` and `target MOS` to be in the RH side panel
* These are in a new section called `Order details` ( side thought: `Info` in `Additional Info` should really have a lowercase `i`)
* the new section is at the top (even though additional details is typically at the top of the RH panel)
* For program based orders, the info blue box is moved to the RH panel also, and shows at the top
* For program based orders, a new section `Program info` is shown under the `Order details` and this has the order type, program and period

![image](https://github.com/user-attachments/assets/4ed8e764-f596-43b9-be7b-cf8e4db4871e)

![image](https://github.com/user-attachments/assets/c585a100-4c98-4a1f-91a2-ba5473aabbff)


![image](https://github.com/user-attachments/assets/5f81527b-124c-4b54-8d87-604d7058d974)

**Comment by lache-melvin** [comment] 2024-08-27 05:46
Closed by #4692

**Closed by lache-melvin** 2024-08-27 05:46 UTC
Labels: bug, platform: android, Severity: Hotfix, needs design

**Comment by mariyamsupply** [comment] 2024-09-03 02:19
Figma link: https://www.figma.com/design/BeluDDB75NzuAW56y2yqHL/Improvements?node-id=1-218&t=HrPLHFLFDXJ2lkhG-1

**Comment by AnushaUp** [comment] 2024-09-16 10:37
🧪 Testing
Tested in OMS `V2.2.02-RC1`


On tablet/small window:

- [ ] Check a regular
- [ ] And a program requisition
- [ ] You can see plenty of rows
- [ ] All the expected info is found in the side panel
