### ISSUE TITLE
Some Master Lists not showing for the same item when looking using Desktop vs. Tablet

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3359] opened 2024-03-20 21:04 UTC
## What went wrong? 😲
 

As a part of 1.7.0 Release testing, I was looking at Master List visibility for one of the items. Using Desktop, the item appears in 2 Master Lists -  and . When looking from a tablet, the item only appears in  (second Master List is missing). 

Desktop is using a different store from tablet, however the Master List is ticked to be visible on the tablet store (). 

## Expected behaviour 🤔

The Master Lists should be matching, regardless of which device you are using to view the item. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Desktop omSupply (I am using SMS Aileu Store on SAMES Datafile)
2. Navigate to Catalogue -> Items -> for example, _Accessory Gutta Percha-Kerr Taper size fine, medium_
3. Note the 2 Master Lists -> SAMES DNFM and SAMES LNS
4. Go to Tablet omSupply (I am using CHC Riamare on SAMES Datafile)
5. Navigate to Catalogue -> Items -> same item (_Accessory Gutta Percha-Kerr Taper size fine, medium_)
6. Note the 1 Master List -> SAMES DNFM

## Your environment 🌱

- Version: v1.7.0
- mSupply version: v7-13-00-Beta25

- Platform: Windows Server 2022 Desktop

- Database type: ?

**Comment by mark-prins** [comment] 2024-03-20 21:31
are you able to save / share the datafile? I'm concerned that this one will be difficult to reproduce, and would like to have the current data just in case!

**Comment by marthakeezy** [comment] 2024-03-20 23:40
Link to omSupply tablet datafile -> https://drive.google.com/file/d/1Tbdkj29KPoikzwK1CwLHbbeSz_QGXnaa/view?usp=drive_link
Desktop datafile is shared on MEGA :)

**Comment by roxy-dao** [comment] 2024-03-22 00:09
Please be careful with sharing data on a public repo D: 
I've removed the screenshots and names

**Comment by roxy-dao** [comment] 2024-03-22 01:06
Looked at the databases.. they're actually using two separate master lists with the same name, so I'm going to close this as not a bug..

**Closed** 2024-03-22 01:08 UTC
Labels: bug, needs triage
