### ISSUE TITLE
Add "Master List" to the View stock filters

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#3184] opened 2024-03-05 19:56 UTC
## Is your feature request related to a problem? Please describe 👀

~Not really a problem.~ It would be great to be able to see stock levels for a particular master list. 

## Describe the solution you'd like 🎁

Add "Master List" to the View stock filters so you can filter your stock by master list. 

### Describe alternatives you've considered 💭

N/A

### Additional context 💌

<img width="747" alt="Screenshot 2024-03-05 at 10 55 02 PM" src="https://github.com/msupply-foundation/open-msupply/assets/74992958/314e8ebe-24b2-4464-a198-ecf53d78939d">

### Moneyworks Jobcode 🧰

None

**Comment by roxy-dao** [comment] 2024-05-28 21:31
Closing as duplicate of #4015 since that is newer and hopefully will get more visibility 👀

**Closed by roxy-dao** 2024-05-28 21:31 UTC
Labels: enhancement, Priority: Should have
