### ISSUE TITLE
Supplier list filter looks buggy

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3448] opened 2024-03-26 09:13 UTC
## What went wrong? 😲
 
When filtering out the suppliers (while creating a new shipment), the way that filter works look wrong
**Note: I'm seeing this mostly in merged names. After merging the names on cloud, this buggy behavior is being seen in my tablet and exe as well!**

## How to Reproduce 🔨

Steps to reproduce the behaviour:
1. In my test-datafile there are three suppliers of same name `Supplier1` (sorry, this is result of merging names: #3276 )
2. Now create new inbound shipment
3. In the window to choose supplier, type `supp` and see error: other irrelevant suppliers show up and the `Supplier1` is more than 3 (more than the existing number of actual suppliers)
4. If you type `Supplier1`, it returns exactly 3 - the actual no. of `Supplier1` names. See [this recording reference](https://github.com/msupply-foundation/open-msupply/assets/59193490/cdea7622-f0c8-4aee-8905-c9e52cf4d08b)

## Additional
I think I have seen this similar issue of list populating with duplicate values before as well in https://github.com/msupply-foundation/open-msupply/issues/2120#issuecomment-1689480993

## Your environment 🌱

- Version: v1.7-rc3
- mSupply version: v713-rc2

- Platform: Android, browser (chrome)

- Database type:

**Comment by roxy-dao** [comment] 2024-03-26 22:16
Might be fixed in #3276

**Comment by roxy-dao** [comment] 2024-04-25 23:35
Going to close this since can't reproduce. Can open again if it does pop up

**Closed by roxy-dao** 2024-04-25 23:35 UTC
Labels: bug, Severity: High
