### ISSUE TITLE
Patient list showing country's specific data instead of generic one

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#5704] opened 2024-12-04 04:13 UTC
## What went wrong? 😲

"NUIC" is a country specific data but is displayed as the generic data for all countries/installs

![Screenshot 2024-12-04 at 5 08 06 PM](https://github.com/user-attachments/assets/06e83ea0-cbfd-4460-aa1f-e420752e2f7c)

## Expected behaviour 🤔

should be a generic name (or using the  label chosen by the country)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Dispensary > Patients List
2. 2nd column

## Your environment 🌱

- Open mSupply Version: 2.03.2
- Legacy mSupply Central Server Version:

- Platform: browser chrome

- Database type:

**Comment by roxy-dao** [comment] 2024-12-04 19:39
Duplicate of #2185

**Closed by roxy-dao** 2024-12-04 19:39 UTC
Labels: bug, needs triage, needs daily triage
