### ISSUE TITLE
Why can't we hold the shipments from stock-transfer?

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3526] opened 2024-04-03 10:35 UTC
## What went wrong? 😲
 
Why can't we hold the shipments from stock-transfer?

## Expected behaviour 🤔
should be allowed to hold (in the same way we can in desktop OG)

## How to Reproduce 🔨

Steps to reproduce the behaviour:
1. Do stock transfer from one store to another
2. In receiving store, open the received Inbound
3. Try to hold that
4. See error: you simply can't
Only while creating new Inbound, you can hold it!

## Your environment 🌱

- Open mSupply Version: v1.7.0-rc4
- Legacy mSupply Central Server Version: v714-dev3

- Platform: browser (chrome), server exe

- Database type: sqlite

**Comment by roxy-dao** [comment] 2024-04-30 02:33
Why would a shipment need to be on hold if it's shipped?

**Comment by Chris-Petty** [comment] 2024-05-01 00:51
I'm not really sure what the workflow for hold is for here, needs user story. @mark-prins ?

At a guess it's for when receiving goods, if things are sitting on a palette outside you want it on hold till something is ready to actually be brought in.

**Comment by mark-prins** [comment] 2024-05-01 01:19
According to the [OG docs](https://docs.msupply.org.nz/other_stuff:virtual_stores#for_stock_transfers_the_supplier_invoice_in_the_receiving_store_should_be):
* Choose Finalised if there is no need to check / alter the quantity received compared to what was sent.
* Choose On hold if the store is being used by mSupply mobile, and the goods receipt needs to be confirmed before receiving.

The behaviour differs for OMS though, as we have a `Delivered` status, and the Inbound shipment is set to `Shipped` - we'd like to retain that as the default, rather than having `Verified` aka `Finalised` set automatically. The 'on hold' seems reasonable though, and particularly if you are sending to OG mobile, as indicated in the docs as the rationale.

So.. yes to having 'on hold' as an option for inbounds. But also.. would be nice to bring through the store preference, and if 'on hold' is checked then set this automatically. 

Side question : I've tried creating an outbound shipment to an OG store and no supplier invoice is created. shouldn't it?

**Comment by Chris-Petty** [comment] 2024-05-02 09:11
Yes an outS should make an SI for the OG store 😓. No special reproduction steps? Datafile? @nisha-dangol I know you are doing a bunch of testing around transfers at the moment so this might ring a bell for you?

**Comment by nisha-dangol** [comment] 2024-05-02 09:20
> Yes an outS should make an SI for the OG store 😓. No special reproduction steps? Datafile? @nisha-dangol I know you are doing a bunch of testing around transfers at the moment so this might ring a bell for you?

The only one I've seen where the SI is missing is when desktop-store is migrated to oms-store scenario: already submitted issue for it as well: #3734
Normal scenarios (stock-transfer between i. oms & oms stores and ii. between oms & desktop stores) rechecked: looks good.

**Comment by clemens-msupply** [comment] 2024-05-06 23:09
> Interestingly in legacy mSupply ALL inbound shipments from transfers are on hold by default, unless both stores are on same site and the supplier has this pref on: ![image](https://private-user-images.githubusercontent.com/7684221/319381507-1a8cd03c-9ba4-4cb6-9277-e83af6ae9cd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMjk4MDUsIm5iZiI6MTcxNTAyOTUwNSwicGF0aCI6Ii83Njg0MjIxLzMxOTM4MTUwNy0xYThjZDAzYy05YmE0LTRjYjYtOTI3Ny1lODNhZjZhZTljZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDZUMjEwNTA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTljZjQxMGE3N2I3OTEwZTJjZmQ4YWVkMWZjZTRmZjEyOTQ1ZDJjYTQ2MWRjNDNjZWYxYjI0YjFmYmZjNmUwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D1KgR30dm9jBDbLzpKnQI9yTfuu6qF9todxJ3Rad5pg)
> 
> In which case it's immediately finalised. I don't know if we should be replicating either of these features. But I do think you should be able to at least manually put it on hold as you suggest @nisha-dangol

I have this option enabled, but the received invoice is not on hold. Why is this not done on mSupply site when doing the transfer, i.e. when creating the supplier invoice?

I could set it on hold when receiving the record, but this feels wrong because I modify the original record as soon as I receive it.

**Comment by nisha-dangol** [comment] 2024-05-20 03:59
Hi @clemens-msupply @mark-prins ; in v2.0.0, I can now see that I can hold the shipments received through stock-transfer - Good. 

But now I can't hold the Inbound shipment that is manually created :
- create a manual new Inbound
- add items
- Hold it
- See error: you still can add/edit that shipment

**Comment by clemens-msupply** [comment] 2024-05-20 21:09
@mark-prins yes can confirm this, but I am a bit confused that the backend doesn't refuse to add items to an invoice that is on hold. Also, the UI didn't have an "onhold" check in before my change. So would like to double-check with you if that was an oversight in the backend/frontend or if it is a bug.

I guess in the UI we just need to add a check if the invoice is on hold in `isInboundDisabled`.

**Comment by mark-prins** [comment] 2024-05-21 05:19
Thanks Clemens - sounds like an oversight to me. Just adding in the on hold check would be good thanks!

**Comment by clemens-msupply** [comment] 2024-05-22 21:34
> Hi @clemens-msupply @mark-prins ; in v2.0.0, I can now see that I can hold the shipments received through stock-transfer - Good.
> 
> But now I can't hold the Inbound shipment that is manually created :
> 
>     * create a manual new Inbound
> 
>     * add items
> 
>     * Hold it
> 
>     * See error: you still can add/edit that shipment

After discussion with @roxy-dao and @mark-prins, we want to keep editing an invoice. On hold just prevent others from doing status changes.

**Comment by roxy-dao** [comment] 2024-05-22 22:38
Closing because of above comment. Issue #3982 to fix not being able to edit Inbound Shipments when status is `Delivered`

**Closed** 2024-05-22 22:39 UTC
Labels: bug, Team Tauhou, Severity: Hotfix, needs design

**Comment by nisha-dangol** [comment] 2024-05-23 03:45
Moving to Done; will be tested as part of #3982
