### ISSUE TITLE
GAPS: Add Cold Storage Type to Item Variants

### ISSUE THREAD

**Issue by jmbrunskill** [msupply-foundation/open-msupply#5249] opened 2024-10-29 21:45 UTC
## Describe the solution you'd like 🎁

Add Cold Storage Type to Item Variants as a drop down/auto complete list?

**Comment by CarlosNZ** [comment] 2024-10-29 23:50
Will also require new "coldStorageType" GraphQL node, so we can get the list, which is also required for [this](https://github.com/msupply-foundation/open-msupply/issues/4367#issuecomment-2445470647)

**Comment by lache-melvin** [comment] 2024-10-30 00:18
Duplicate of #4368

**Closed by lache-melvin** 2024-10-30 00:18 UTC
Labels: enhancement, Team Piwakawaka, feature: GAPS

**Comment by marthakeezy** [comment] 2024-11-03 22:46
As this is a duplicate, testing will be done under #4368 

Moving to Done ✅
