### ISSUE TITLE
After merging names, type customers & suppliers are totally discarded 

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3449] opened 2024-03-26 09:19 UTC
## What went wrong? 😲
 
After merging names, type customers & suppliers are totally discarded. 
Since after merging, oms is showing a strict customer under Supplier list (and vice versa), can I call this Severity:high!

## Expected behaviour 🤔
Don't mix up the customers & suppliers?

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. Create two customers (make sure the boolean customer is only checked while creating) and sync
2. In oms, see the two newly created customer under the Distribution>Customers list. Also note that they do not appear under Suppliers list
3. Now on desktop cloud, merge those two customers and sync
4. Open the Suppliers list
5. See error: the merged customer (strictly-customer) name now appears as Supplier as well!

## Your environment 🌱

- Version: v1.7-rc3
- mSupply version: v713-rc2

- Platform: Android

- Database type:

**Comment by Chris-Petty** [comment] 2024-04-02 23:36
Done in #3450

https://github.com/msupply-foundation/open-msupply/blob/e5b989e43a71a1609684f765e6d15a8fc2c045f9/server/service/src/sync/translations/special/name_merge.rs#L116-L133

**Comment by Chris-Petty** [comment] 2024-04-02 23:38
Actually no - I reread the reproduction steps this issue is different (two customers merged somehow become supplier). I will retest and see if I can reproduce...

**Comment by Chris-Petty** [comment] 2024-04-02 23:58
Hmm I can't reproduce, perhaps fixed with recent changes. @nisha-dangol try again?

https://github.com/msupply-foundation/open-msupply/assets/7684221/12a514f6-7452-4265-9422-36ab87bb2e90

**Closed by Chris-Petty** 2024-04-02 23:58 UTC
Labels: bug, Team Tauhou, Severity: High

**Comment by nisha-dangol** [comment] 2024-04-03 11:18
> Hmm I can't reproduce, perhaps fixed with recent changes. @nisha-dangol try again?
> 
You're right; can't replicate it again in the new v1.7.0-rc4 exe!
