### ISSUE TITLE
Cannot load Item Usage report: error making API request

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5298] opened 2024-11-04 02:14 UTC
## What went wrong? 😲

Cannot load Item Usage report

https://github.com/user-attachments/assets/663f4b2c-1438-45d8-92c1-07c80c89cd02

## Expected behaviour 🤔

Can load the report

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Reports -> Item Usage
2. See error

## Your environment 🌱

- Open mSupply Version: V2.4.0-test1
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Browser (Google) on a laptop

- Database type: SQLite3

**Comment by lache-melvin** [comment] 2024-11-04 02:24
Network error would suggest your server is offline @marthakeezy! However, the loading button should go away after you get the error message, maybe #4587 isn't actually fixed?

**Comment by marthakeezy** [comment] 2024-11-04 02:25
Hmm.. Should the rest of reports be working if my server is offline?

**Comment by lache-melvin** [comment] 2024-11-05 02:39
Going to close this one as duplicate of #5312 as the other one has more context!

**Closed by lache-melvin** 2024-11-05 02:39 UTC
Labels: bug, needs triage, Severity: Normal, feature: reports
