### ISSUE TITLE
Cold chain: Temperature logs are not synced from CCA to OMS while a breach is active

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#2537] opened 2023-11-23 05:52 UTC
## What went wrong? 😲

Temperature logs are not coming across from CCA to OMS while there's an active breach on CCA. 

As soon as the excursion is resolved i.e. returns below the threshold (note, not breach acknowledged), then log syncing resumes. 

Observed on both tablet and Windows OMS. 

CCA during active breach: 

![telegram-cloud-photo-size-1-5113892675039374097-y](https://github.com/msupply-foundation/open-msupply/assets/19318937/e9ec087b-5b0f-4923-87e8-f768981bf607)

OMS during active breach: 

![telegram-cloud-photo-size-1-5113892675039374098-y](https://github.com/msupply-foundation/open-msupply/assets/19318937/02718363-8421-4565-aa82-b980e806b7b0)

Note: the breach duration threshold is 4 mins, so the first 2 logs (17:54:16 and 17:56:16) came across to OMS before they were flagged as part of a breach. 

CCA after breach resolved: 

![telegram-cloud-photo-size-1-5113892675039374105-y](https://github.com/msupply-foundation/open-msupply/assets/19318937/d717f19c-6b16-45d0-b986-10d9bb659fd7)

OMS after breach resolved: 

![telegram-cloud-photo-size-1-5113892675039374106-y](https://github.com/msupply-foundation/open-msupply/assets/19318937/00cc183f-a888-4097-ae93-e3d501bcc1b3)

## Expected behaviour 🤔

Logs should come through allll the time

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Sync CCA to OMS (tablet or Windows)
2. Note logs coming through correctly
3. Trigger an breach on a sensor
4. Note that logs for that sensor stop coming through to OMS (other sensors will continue syncing as normal)
5. Resolve the breach
6. Note that logs start coming through again

## Your environment 🌱

 - CCA version: 0.5.6-rc1
 - OMS Version: 1.5.02
 - Platform:
   - [x] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [x] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by mark-prins** [comment] 2023-12-05 21:21
unable to reproduce the issue with my local testing. am using the current develop branch of cold chain app with the current develop branch of omSupply. results show up in omSupply correctly whether in breach or not.

**Comment by adamdewey** [comment] 2023-12-14 02:26
I'm still getting this with CCA 0.5.6 and OMS 1.5.03 - maybe I can show you tomorrow @mark-prins ?

**Comment by mark-prins** [comment] 2023-12-14 02:28
thanks. will retest with 1.5.03 as well

**Comment by nisha-dangol** [comment] 2024-02-26 06:42
Have checked this with oms v1.6.2 exe and coldchain 0.5.6. I can see the logs even when the breach is active, looks fixed in v1.6.2! Can close this!

**Closed by nisha-dangol** 2024-02-26 06:42 UTC
Labels: bug
