### ISSUE TITLE
Date picker formatting regression

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#3918] opened 2024-05-16 04:24 UTC
## What went wrong? 😲
Date picker for CCE sensor monitoring has changed to something slightly odd!

See current behaviour:

https://github.com/msupply-foundation/open-msupply/assets/90807420/b939439f-1313-4a89-b81b-51dd9709b2be

Previously it looked like this:
![date reformat](https://github.com/msupply-foundation/open-msupply/assets/90807420/fd354997-8b1a-499c-9337-c3b3913eb348)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to ColdChain -> Monitoring
2. Select Date picker and see odd formatting

## Your environment 🌱
Android tablet
Issue not occurring on desktop

**Comment by CarlosNZ** [comment] 2024-05-19 20:59
My Android build keeps crashing, and I can't replicate this in any other environment, so haven't been able to investigate this properly. I guess leave it in "needs triage" for now, but I'll try and have another when I can get Android working again. It's odd that even in the "correct" view above it doesn't look right. I'd be interested to see if it's just in the Cold Chain module or if it's all Date pickers -- @fergie-nz can you confirm?

**Comment by adamdewey** [comment] 2024-05-19 21:53
@CarlosNZ - agree, the 'correct' view also looks like a bug!

**Comment by roxy-dao** [comment] 2024-05-22 23:21
Triage: Might be because of the screen size.

**Comment by roxy-dao** [comment] 2024-08-19 18:28
Looks normal now in 2.2.0-RC5, can anyone else reproduce the regression or can we close this issue? 
![Screenshot_20240819-202712](https://github.com/user-attachments/assets/115052a0-b6ed-4424-ba00-a069f882ea11)

**Comment by adamdewey** [comment] 2024-08-19 21:18
@roxy-dao - in Cold Chain > Monitoring it still doesn't look good (e.g. the time is massive compared to the date)

![telegram-cloud-photo-size-1-5051257534874234274-y](https://github.com/user-attachments/assets/cc532f89-0a91-4aa8-957e-586db479e527)

**Comment by mark-prins** [comment] 2024-08-19 21:24
The original problem isn't happening now! I could repro easily by using inspector and going to mobile view, but now it doesn't happen.

Soz @adamdewey - while I agree and the font sizes look terrible, it isn't the problem that was raised, so I'm gonna just close this issue

**Closed by mark-prins** 2024-08-19 21:24 UTC
Labels: bug, platform: android, Priority: Should have, Team Piwakawaka, Severity: Low

**Comment by adamdewey** [comment] 2024-08-19 21:27
All good, shifted it to here: https://github.com/msupply-foundation/open-msupply/issues/4628
