### ISSUE TITLE
App crashes when inbound shipment hold tick is ticked or unticked!

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#5021] opened 2024-10-07 02:24 UTC
## What went wrong? 😲

App crashing - react hook rendering issue count.

## Expected behaviour 🤔

No crashing

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to inbound shipments
2. Click on a shipment
3. Scroll down to untick or tick 'hold' button

https://github.com/user-attachments/assets/7c968c63-168e-4eca-9a6a-2f992073d1ec

## Your environment 🌱

- Open mSupply Version: 2.3.0

**Comment by lache-melvin** [comment] 2024-10-07 19:40
What RC version are you using here @fergie-nz? I think this was fixed in #4942, which went in RC5 - I can't reproduce?

**Comment by fergie-nz** [comment] 2024-10-07 21:27
Closing as fixed! I must have been on an older version. (develop?!?)

**Closed** 2024-10-07 21:27 UTC
Labels: bug, needs triage

**Comment by marthakeezy** [comment] 2024-10-17 22:47
Doesn't happen in V2.3.0 - moving to Done ✅
