### ISSUE TITLE
Updated item prices do not get reflected in Outbound Shipments

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5111] opened 2024-10-14 05:43 UTC
## What went wrong? 😲

Scenario: I am creating an Outbound Shipment and notice the item prices need to be updated. I navigate to Inventory -> View Stock to update the item's Sell Price and Cost Price and neither get updated in the newly created Outbound Shipment. 

After a discussion with @mark-prins, we agreed it would make sense for the updated prices to show up for any status up until Shipped -> e.g. if the stock hasn't left the premises, there should be an option to update the Outbound Shipments if needed (for New, Allocated and Picked). 

- **Solution 1** -> all non-shipped Outbound Shipments get updated automatically after the price change. 

- **Solution 2** -> Outbound Shipments stay as they are, but upon price change the user is prompted with a checkbox they can tick if they want all Outbound Shipments updated with the new information. Something like 'this item is currenly added to x outbound shipments. Would you like to update them with the changes?'

- **Solution 3** (which should be available regardless of the top two solutions) -> non-shipped outbound shipments Pack Sell Price cell should be editable, if the user wants it changed on the spot instead of looking up the item in Inventory. However, it should be clear if the change is one-off or a blanket change for the product. 

Note: in OG mSupply, there is an option to re-lookup the price if the item is added to an outbound shipment. If you change the cost price or the sell price, only cost price gets updated. Technically there is a workaround in omSupply such as deleting the item and adding it again to see the changes, so setting the severity as Normal. 

Video of the behaviour can be found [here](https://drive.google.com/drive/folders/1O3mjhUUEBN9ml0tV5nfNiTZ1B4J5nImY) :)

## Expected behaviour 🤔

Described above :)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Distribution -> Outbound Shipment
2. Create a new Outbound Shipment -> add an item
3. Do not change the status
4. Go to Inventory -> View Stock and change the item's Sell and Cost prices
5. Navigate back to the Outbound Shipment -> see the information is the same

## Your environment 🌱

- Open mSupply Version: V2.3.0-RC8
- Legacy mSupply Central Server Version: V7.10.17

- Platform: Tablet (apk)

- Database type: SQLite3

**Comment by mark-prins** [comment] 2024-10-14 21:41
Note: Solution 3 requires this store preference in OG

<img width="504" alt="image" src="https://github.com/user-attachments/assets/dd188977-fa69-4ced-9e3a-ae5bdc9e149e">

and an item preference to be set

<img width="315" alt="image" src="https://github.com/user-attachments/assets/75e4cebc-abae-4e88-b4fd-662218ddc239">

And then there's this pref

<img width="315" alt="image" src="https://github.com/user-attachments/assets/54035596-242b-4144-9426-a938b4e4bb7b">


which is to say that I wouldn't want the Solution 3 without some controlling preferences; it shouldn't be available to all by default

**Comment by roxy-dao** [comment] 2024-10-14 22:24
Duplicate of #3703

**Comment by lache-melvin** [comment] 2024-10-15 02:03
Leaving this open for triage team to discuss, as the solutions here are different to those in #3703 - then we should close one 🙏

**Comment by marthakeezy** [comment] 2024-10-16 21:31
Adding a comment here after testing backdating prescriptions: 

I seem to be able to issue prescription with a batch that is on-hold

Prescription was created before the item was on-hold, e.g. I made changes to the item when the prescription was already picked but not yet verified

Along the same lines, if I change the batch's expiration date, the changes do not get reflected in the prescription

Will be good to agree on a consistent behaviour across the omSupply platform!

**Comment by andreievg** [comment] 2024-10-17 22:49
Refinement, basic rule is that once invoice line is created it holds the snapshot of stock line on the date of creation. Some further discussion about stock line cost price in another issue, still to be validated against concrete use cases

**Closed by andreievg** 2024-10-17 22:49 UTC
Labels: bug, Severity: Normal, Needs refinement
