### ISSUE TITLE
Handle historic outbound -> inbound shipments translations

### ISSUE THREAD

**Issue by clemens-msupply** [msupply-foundation/open-msupply#3120] opened 2024-02-28 21:54 UTC
From: https://github.com/msupply-foundation/open-msupply/issues/608

When store is created from normal name and that store becomes omSupply site, historic outbound shipments will sync to that store, could result in mass creation of inbound shipments

And https://github.com/msupply-foundation/open-msupply/issues/608#issuecomment-1480256897:

> Chris Petty, [23/03/2023 at 9:50:13 AM]:
>...A common story in the wild is to take a regular facility name (a pharmacy not on mSupply yet), create a store for it a nd sync it to a new mobile device. Imminently these devices will be often installed with omSupply! 🎉
> 
>Part of the sync initialisation code will send all the past customer invoices relating to the name to the omsupply site. As it is, this could include years of customer invoices... I don't think I've brought this up before, so my question is; do we do anything to not generate inbound shipments from customer invoices that are ancient?
>
> mSupply had a similar issue a couple years ago, but potentially not as bad. The solution there was that if a store/site user opened supplier invoice sent from another store, it'd check the creation time of that invoice against the logged time of when the store was created.
>
> The store table does have a created_date - omSupply could use this to put a halt on looking too far back when creating transfers (if it doesn't already!).
>
> Mark Glover, [23/03/2023 at 9:58:06 AM (23/03/2023 at 9:58:39 AM)]:
> I might be misunderstanding what you have said, but I'm pretty sure that behaviour used to be that historic supplying store CIs do NOT get synced to the new store as SIs (PNG did 300 sites last year and they did not get any old SIs.) We certainly don't want ancient SIs appearing in the customer store. AFAIK, only sending store CIs created AFTER creation of the receiving store get 'sent' (regardless of sync).
>
> I would LOVE the store table getting a created_date This would be very helpful in reporting deployment progress.

### Moneyworks Jobcode 🧰

OMS:MIGRT

**Comment by DhanyaHerath** [comment] 2024-02-28 22:18
Duplicate of https://github.com/msupply-foundation/open-msupply/issues/2760?
That one seems like it has more info

**Closed** 2024-02-29 01:35 UTC
Labels: enhancement, Migrating Existing Mobile, Migrate Existing Desktop, Team Tauhou
