### ISSUE TITLE
omSupply central sync step 

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#3119] opened 2024-02-28 21:41 UTC
If omSupply central is not reached we currently show an error, but allow sync to go through. For 1.7.0 i think we can hide the error or make it less obvious (technically we don't need omSpply central for 1.7.0 to work, only when pack variants are used, so don't really want to scare users with this error, or update every installation to have the omSupply central).

We also want a sync step for omSupply central pull

**Comment by jmbrunskill** [comment] 2024-03-22 04:09
Duplicate of https://github.com/msupply-foundation/open-msupply/issues/3266 ?

**Closed** 2024-04-24 03:38 UTC
Labels: enhancement, feature: pack variant, Team Ruru 🦉
