### ISSUE TITLE
Cold Chain: The selector is misaligned with the 'Chart' button when first logging into omSupply

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3054] opened 2024-02-23 01:36 UTC
## What went wrong? 😲
 

When you first log into omSupply, and go under ColdChain -> Monitoring, you will notice the selector (black line indicating which tab is selected) is skewed to the left and is misaligned with the 'Chart' button. 

## Expected behaviour 🤔

The indicator should be directly under the text, not to the left. 

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to omSupply -> ColdChain -> Monitoring
2. Do not click on the tab -> instead, you will see the bug instantly as it appears to the left of 'Chart'

![image](https://github.com/msupply-foundation/open-msupply/assets/153777484/18922b9a-446d-4a55-af22-f54a1c679807)

In comparison, this is what it should look like normally:

![image](https://github.com/msupply-foundation/open-msupply/assets/153777484/3c82b07c-5546-4a24-be33-68f3790249da)

## Your environment 🌱

- Version: 1.6.02
- Platform:
  - android (tablet) - Samsung Galaxy A8

**Comment by Chris-Petty** [comment] 2024-02-27 01:16
Probably related: https://github.com/msupply-foundation/open-msupply/issues/777

**Comment by roxy-dao** [comment] 2024-03-13 00:07
Close as duplicate of #3213

**Closed by roxy-dao** 2024-03-13 00:07 UTC
Labels: bug, feature: coldchain, Severity: Low
