### ISSUE TITLE
Electron client ssl error

### ISSUE THREAD

**Issue by andreievg** [msupply-foundation/open-msupply#1198] opened 2023-02-17 02:26 UTC
## What went wrong? 😲

Ssl error when connecting to server from electron client

## Expected behaviour 🤔

No error

## How to Reproduce 🔨

`yarn electron:start` <- from client dir
`cargo run` <- from server dir

try connect to server

**Comment by roxy-dao** [comment] 2024-05-23 03:33
Closing since can't reproduce

**Closed by roxy-dao** 2024-05-23 03:33 UTC
Labels: bug, Priority: Nice to Have
