### ISSUE TITLE
Stocktake: bug when setting up expiry dates via calendar window 

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#2775] opened 2024-01-18 21:52 UTC
## What went wrong? 😲

During the stocktake, when selecting an expiry date for a stock line, if you use use the calendar window to change the input, sometimes it doesn't update the date correctly.

Here is a video of the issue happening in only a few lines of the stocktake:

https://github.com/msupply-foundation/open-msupply/assets/132425096/2052feca-2b65-476e-a695-c06701ebd4bd

If we type the dates, the problem doesn't occur.

The problem also occurs when inputing the data on that field for the first time:

Uploading Screen Recording 2024-01-19 at 10.49.45 AM.mov…

## Expected behaviour 🤔

The date field should update if you use the calendar window.

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to 'Inventory'
2. Click on 'Stocktake' > New
3. Select one row and try to change the expiry date using the calendar window

## Your environment 🌱

OMS demo server : https://demo-oms.msupply.org/

 - Version: 1.6.00
 - Platform: 
   - [ ] android (tablet)
   - [x] browser (Chrome)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by DhanyaHerath** [comment] 2024-01-23 21:48
Hmm, I wasn't able to reproduce this even on the demo server :(

**Comment by regotaina** [comment] 2024-01-23 21:58
> Hmm, I wasn't able to reproduce this even on the demo server :(

Sometimes it appears, sometimes it doesn't. I wonder why :/

This was also recorded on the day we've done the demo (18/01). Should we keep an eye on it? 

https://github.com/msupply-foundation/open-msupply/assets/132425096/9a51cdce-89df-494e-865d-db99de51f25b

**Comment by roxy-dao** [comment] 2024-02-08 01:09
I couldn't reproduce this locally or on the demo... but did find another bug where the calendar selection modal moves, so you can't select a date......

https://github.com/msupply-foundation/open-msupply/assets/61820074/125fc709-e47b-4ccc-9fef-8ff3eacd82c7

**Comment by jmbrunskill** [comment] 2024-02-12 21:03
@DhanyaHerath @regotaina Should we close this if we can't repro?

**Comment by roxy-dao** [comment] 2024-02-12 21:12
Yeah can close and reopen if someone can reproduce it...

**Closed** 2024-02-12 21:44 UTC
Labels: bug, Section: Stocktake
