### ISSUE TITLE
Trying to increase the issue-quan in Prescription window shows wrong `available(packs)` and thus can't increase the quan despite the stocks available

### ISSUE THREAD

**Issue by nishaDangol-Sussol** [msupply-foundation/open-msupply#4541] opened 2024-08-08 09:59 UTC
## What went wrong? 😲
Trying to change/increase the issue-quan in Prescription window shows wrong `available(packs)` and thus can't increase the quan despite the stocks available
 

## Expected behaviour 🤔
same behavior like in the OS; should be able to increase the quan in Prescription as well as long as I'm entering sth <= actual SoH

## How to Reproduce 🔨
Steps to reproduce the behaviour:
1. There’s 5 SoH.
2. I issue out 3 first. 
3. now I try to change quan
4. as long as it’s anything <=2 (remaining=5-3=2), it’s fine
5. but when i try to change it to >2, sth like 4, now it won’t let me. The only way to increase it to 4 is delete that line and put 4 again. 
6. You can try the above scenario in OS, you'll see no problem there. Issue's only in Prescription where `available(packs)` is changing unlike in the OS

## Recording

https://github.com/user-attachments/assets/97db2d29-86e7-4b6a-824f-021276e2b6fe

## Your environment 🌱

- Open mSupply Version: v2.2.00-RC1
- Legacy mSupply Central Server Version: v7-16-04

- Platform: oms-server + browser(chrome)

- Database type: sqlite

**Comment by andreievg** [comment] 2024-08-09 00:12
Linked: https://github.com/msupply-foundation/open-msupply/issues/3252

I am not sure if we can make quick changes now until we clarify the expected behaviour of this modal, lets revisit in the weekly triage meeting

**Comment by roxy-dao** [comment] 2024-08-15 19:28
Was done this way because some pharmacists don't finalise prescriptions (so picked was being treated as verified)... but can change it to have available packs shown the same as outbound

**Comment by andreievg** [comment] 2024-08-16 02:21
Looks like you should be able to issue 5 if that's what is available.

**Comment by andreievg** [comment] 2024-08-16 02:21
I think this was fixed in outbound

**Comment by mark-prins** [comment] 2024-08-16 02:46
Possibly similar to #3326

**Comment by roxy-dao** [comment] 2024-08-16 05:29
> Possibly similar to #3326

It's because of `createDraftPrescriptionLine`

**Comment by roxy-dao** [comment] 2024-08-19 05:16
Closed in #4609

**Closed by roxy-dao** 2024-08-19 05:16 UTC
Labels: bug, Severity: Hotfix

**Comment by AnushaUp** [comment] 2024-09-17 08:05
# 🧪 Testing
Tested in V2.2.2.


- [ ] Have an item with 10 (or so) stock on hand. 
- [ ] Go to prescriptions
- [ ] Issue 3 to patient
- [ ] You should still have 10 available stock to issue.

2.
- [ ] Try issue all the item to the patient
- [ ] Batch shouldn't disappear and you should still be able to edit batch.

**Comment by AnushaUp** [comment] 2024-09-18 04:02
> * Batch shouldn't disappear and you should still be able to edit batch.

@roxy-dao Batch is shown but cannot be edited

**Comment by AnushaUp** [comment] 2024-09-19 08:22
Issue mentioned above is fixed. Moving this to done✅
