### ISSUE TITLE
Equipment -> Storage Volume is not displayed fully/nicely on Android tablet

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3748] opened 2024-05-02 23:50 UTC
## What went wrong? 😲
 

When navigating under Equipment -> specific equipment item -> Properties, the Storage Volume lines do not show up nicely and are split between multiple lines. 

<img width="1089" alt="GH" src="https://github.com/msupply-foundation/open-msupply/assets/153777484/309e1b9e-caa4-46b1-bf3e-f8c9b778bb88">

And another example from Adam: <img width="1065" alt="Screenshot 2024-05-03 at 11 45 38 AM" src="https://github.com/msupply-foundation/open-msupply/assets/153777484/b04a467e-71b9-400d-a6cf-acb4775ffb66">

## Expected behaviour 🤔

It would be ideal to display them in a neat and tidy way, e.g. maybe on one or 2 lines?

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Equipment -> click on a specific Equipment item
2. Navigate under Summary -> Properties
3. See the fomratting

## Your environment 🌱

- Open mSupply Version: 2.0.0 RC2
- Legacy mSupply Central Server Version: v7.14

- Platform: Galaxy A8 Tablet (Android)

- Database type: ?

**Comment by roxy-dao** [comment] 2024-07-02 05:24
Closing as duplicate of #4348 <- has more details and covers the broader app

**Closed by roxy-dao** 2024-07-02 05:24 UTC
Labels: bug, Priority: Nice to Have, Severity: Low, feature: CCEI
