### ISSUE TITLE
CCEI: Model field in Catalogue appears editable

### ISSUE THREAD

**Issue by adamdewey** [msupply-foundation/open-msupply#4132] opened 2024-06-12 03:07 UTC
## What went wrong? 😲

It seems like the model field in the Asset Catalogue is editable, but it shouldn't be: 

![image](https://github.com/msupply-foundation/open-msupply/assets/19318937/88e24986-2044-402f-a62b-21b0af9675b3)

## Expected behaviour 🤔

Field shouldn't appear to be editable

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

- Open mSupply Version: 2.1.00
- Legacy mSupply Central Server Version: 2.0.0

- Platform:

- Database type:

**Comment by lache-melvin** [comment] 2024-06-20 21:04
Duplicate of #4204, closed by #4210

**Closed by lache-melvin** 2024-06-20 21:04 UTC
Labels: bug, Priority: Nice to Have, feature: CCEI
