### ISSUE TITLE
Something wrong when entering prices in Inbound Shipment (possibly other views ?): entered 100 but system records 1,00

### ISSUE THREAD

**Issue by richardmoizeau** [msupply-foundation/open-msupply#3180] opened 2024-03-05 19:49 UTC
## What went wrong? 😲

Something wrong when entering prices in Inbound Shipment (possibly other views ?): 

- entered 10000 but system records 100,00

- entered 100 but system records 1,00

Note: I'm using a french keyboard (AZERTY) where we use "," (coma) instead of "." (dot) to separate the decimals. 

https://github.com/msupply-foundation/open-msupply/assets/74992958/2dececea-a6bd-4ffe-8623-091dca95fbbc

## Expected behaviour 🤔

N/A

## How to Reproduce 🔨

See video

## Your environment 🌱

- Version: 1.7.00
- mSupply version: 

- Platform: browser (chrome)

- Database type:

**Comment by roxy-dao** [comment] 2024-03-05 19:50
Closing as duplicate of #2918

**Closed by roxy-dao** 2024-03-05 19:50 UTC
Labels: bug
