### ISSUE TITLE
Cold Chain: Location Filter displays unnecessary text when interacted with

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#3289] opened 2024-03-14 04:16 UTC
## What went wrong? 😲
 

When pressing on Location filter to enter text, unnecessary text is displayed in the background

![image](https://github.com/msupply-foundation/open-msupply/assets/153777484/1a3eb97d-fa25-47ac-93c3-594fe47f8268)

## Expected behaviour 🤔

No text should be displayed

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Cold Chain -> Monitoring -> Log
2. Click on Filters and select 'Location'
3. Click on the text box to enter text
4. See text

## Your environment 🌱

- omSupply version 1.7.00

**Comment by roxy-dao** [comment] 2024-03-14 23:53
![Screenshot 2024-03-15 at 12 53 09](https://github.com/msupply-foundation/open-msupply/assets/61820074/dc593fef-f648-400f-a33a-16397c1845f0)
My one seems to show the localisation fine 🤔

**Comment by marthakeezy** [comment] 2024-03-14 23:58
Just checked the field again - it seems to have fixed itself! Displaying all good on my end now

![image](https://github.com/msupply-foundation/open-msupply/assets/153777484/51fcf214-7f98-4131-b074-1dec5d13537f)

**Comment by roxy-dao** [comment] 2024-03-15 00:00
Closing since can't reproduce

**Closed by roxy-dao** 2024-03-14 23:59 UTC
Labels: bug, Severity: Normal

**Comment by marthakeezy** [comment] 2024-03-15 00:02
No testing needed as the issue seems to have resolved itself - will keep an eye out in case it occurs again in the future ✅
