### ISSUE TITLE
UI bug in coldchain > Monitoring section

### ISSUE THREAD

**Issue by AnushaUp** [msupply-foundation/open-msupply#3521] opened 2024-04-03 07:22 UTC
## What went wrong? 😲
The undeline is not responsive when not full screen in the desktop and browser both
![Screenshot 2024-04-03 at 12 55 00 pm](https://github.com/msupply-foundation/open-msupply/assets/115983430/4ffb9b6f-f8d6-4be0-a9d9-e140750d091f)

https://github.com/msupply-foundation/open-msupply/assets/115983430/568122c0-c747-4464-b25e-f01e6584c64c

## Expected behaviour 🤔
Should be responsive

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Coldchain setup
2. Navigate to coldchain> monitering
3. Exit full screen

## Your environment 🌱

- Open mSupply Version: v1.7.00-rc4
- Legacy mSupply Central Server Version:

- Platform: Desktop and browser

- Database type:

**Comment by roxy-dao** [comment] 2024-04-03 22:06
Duplicate of #3213 and fix should be in 2.0.0

**Closed by roxy-dao** 2024-04-03 22:06 UTC
Labels: bug
