### ISSUE TITLE
Interaction between months entered and years

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#5003] opened 2024-10-04 04:02 UTC
## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Immunisation Programs > Vaccine Course
2. Add a dose to the vaccine course
3. Enter months in the months column and see years change.

I believe this is occuring because when months more than 12 are added, it is aggregated to years. But is confusing to enter:

https://github.com/user-attachments/assets/6870fc35-a5d6-48b5-a994-fbb8c0bd20d8

## Your environment 🌱

Open mSupply Version: 2.3.00-RC5 - Central Server
Legacy mSupply Central Server Version:
Platform: On samsung 2.3.00-RC5, but no different to desktop

**Comment by lache-melvin** [comment] 2024-10-04 04:39
I think was intended as helpful when entering from 0 (can type 18 months, maps to 1 year 6 months) but agree is more confusing in this case than I think its worth.

Quick fix for release: set a max on the input - 11?

**Comment by lache-melvin** [comment] 2024-10-08 20:06
Closed by #5039

**Closed by lache-melvin** 2024-10-08 20:06 UTC
Labels: bug, Team Piwakawaka, Severity: Normal, feature: vaccine card

**Comment by marthakeezy** [comment] 2024-10-17 22:48
V2.3.0 has been released so moving to Done ✅

**Comment by marthakeezy** [comment] 2024-10-23 22:34
Hey team, just giving this one a test - is it important to be able to add 11.x months? Seem to be able to do it for any other number, e.g. 8.5, 10.9 but 11 is capped

https://github.com/user-attachments/assets/a649a787-0b07-4c8e-9bda-df898d73f1fe

**Comment by lache-melvin** [comment] 2024-10-23 22:39
Yep per comment above - max was set to 11 for this release. 

The only real use case for the decimals is 1.5 months (6 weeks) or 4.5 months (14 weeks), so we're pretty safe.

There is another issue to refactor this UI at some point anyway #4928
