### ISSUE TITLE
iSC/Cold chain/GAPS: changes to item variants don't show in Logs

### ISSUE THREAD

**Issue by marthakeezy** [msupply-foundation/open-msupply#5499] opened 2024-11-21 02:29 UTC
## What went wrong? 😲

When making changes to an item's variant, the changes don't show in Logs

https://github.com/user-attachments/assets/3e7ec90a-29f3-4bf7-8be7-aa5a3854af38

## Expected behaviour 🤔

Changes should show just like the rest of the fields :)

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Go to Catalogue -> Items
2. Select an item to test with and add a few variants to it
3. Go to Inventory -> View Stock
4. Locate your item (if it has stock) or add stock to it to be able to see it
5. Once added, click into the item and play around with the Item Variant field (e.g. remove it, change from one to another etc)
6. If you go to Log, you won't be able to see the changes there

## Your environment 🌱

- Open mSupply Version: V2.4.0-RC2
- Legacy mSupply Central Server Version: V7.18.11

- Platform: Google Chrome (browser for Mac)

- Database type: SQLite3

**Comment by mark-prins** [comment] 2024-11-28 19:56
The log is for changes to the item, and technically the item variant is a separate entity. I think we should close this issue and we'll bring in an enhancement later to add logs for variants

**Comment by mark-prins** [comment] 2024-11-28 20:04
duplicate of https://github.com/msupply-foundation/open-msupply/issues/5341?

**Comment by andreievg** [comment] 2024-11-28 22:29
Agree, it's duplicate, thanks

**Closed by andreievg** 2024-11-28 22:29 UTC
Labels: enhancement, needs triage, feature: GAPS
