### ISSUE TITLE
Outbound Shipment: odd display when unit price  =0

### ISSUE THREAD

**Issue by regotaina** [msupply-foundation/open-msupply#3402] opened 2024-03-24 22:49 UTC
## What went wrong? 😲

For Outbound Shipment when unit price = 0, the display looks a bit odd. 

<img width="1277" alt="Screenshot 2024-03-25 at 11 47 03 AM" src="https://github.com/msupply-foundation/open-msupply/assets/132425096/324ba7fa-9e1c-47bf-91b5-d4ef9a933016">

## Expected behaviour 🤔

Unit price = 0

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Choose an item with unit price =0
2. Go to 'Outbound Shipment'
3. Click on 'Add item' and choose the item from step number 1
4. Input any quantity and click "Ok'
5. See error on item line

## Your environment 🌱

- Version: 1.7 
- mSupply version: V7.13

- Platform: Desktop app

**Comment by roxy-dao** [comment] 2024-03-26 00:07
Can't seem to reproduce this 👀

**Comment by andreievg** [comment] 2024-05-07 00:20
@roxy-dao mentioned that she can't reproduce, and @CarlosNZ thinks it might have been fixed, let's see if it pops up again. closing for now

**Closed by andreievg** 2024-05-07 00:20 UTC
Labels: bug, Severity: Normal
