### ISSUE TITLE
Sync Issue - Problem in sending transactions from OMS v1.7 to mSupply v7.15.XX

### ISSUE THREAD

**Issue by RachanaKunwar** [msupply-foundation/open-msupply#4290] opened 2024-06-26 09:34 UTC
## What went wrong? 😲

There is a problem in sending transactions from OMS store v1.7 to mSupply store  v7.15.XX although the sync is working fine.  

## Expected behaviour 🤔
Transactions between the stores should have synced. No issue between OMS to OMS

Cerb: https://cerb.msupply.org/profiles/ticket/AT-5139-KC

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. Have a mSupply server v7.15.XX setup that contains both mSupply and OMS sites. 
2. Create any transaction from OMS site to the mSupply store X. Eg. create an internal order for mSupply store X. 
3. Click on 'Sync now'
4. Check the transaction on the mSupply server for that particular mSupply store X. Here no requisition has been created.
5. See an error...

## Your environment 🌱

- Open mSupply Version: v1.7
- Legacy mSupply Central Server Version: v7.15.06

- Platform:

- Database type:
- -

**Comment by andreievg** [comment] 2024-06-26 23:13
This sound very serious, need to try and replicate asap and then figure out what the issue is, then decide which existing versions to patch

**Comment by andreievg** [comment] 2024-06-26 23:36
I tried making internal order and outbound shipment from omSupply store to a store active on mSupply, this works fine (both supplier invoice and customer requisition received), next step is to try to do it for a store on mSupply remote site

**Comment by andreievg** [comment] 2024-06-27 00:08
Created a new site for mSupply, and tried creating internal order and shipments between omSupply store and mSupply store on a new site, in both directions, works fine. omSupply 1.7.0, mSupply 7.15.06

**Comment by andreievg** [comment] 2024-07-01 01:09
Bug is fixable in mSupply: https://github.com/msupply-foundation/msupply/issues/14904

**Comment by JonnaQuismundo** [comment] 2024-07-03 21:46
> Bug is fixable in mSupply: [msupply-foundation/msupply#14904](https://github.com/msupply-foundation/msupply/issues/14904)

closed in mSupply `V7-15-12`

**Closed by JonnaQuismundo** 2024-07-03 21:46 UTC
Labels: bug, Team Ruru 🦉, Severity: Hotfix
