### ISSUE TITLE
Improve location changes logs

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#4449] opened 2024-07-24 10:14 UTC
## What went wrong? 😲
When changing location of an existing stock from A to B, the log should say location changed from A to B, not A's ID to B's ID

## Expected behaviour 🤔
When changing location of an existing stock from A to B, the log should say location changed from A to B, not A's ID to B's ID

## How to Reproduce 🔨

Steps to reproduce the behaviour:
1. Go to `View stocks`
2. Select any existing stock line
3. Change its location from A to B suppose and save
4. Now see Log tab
5. See error: the message looks messy
<img width="1220" alt="image" src="https://github.com/user-attachments/assets/09af14bc-6f7b-4621-82f2-68de6cb00d26">

## Your environment 🌱

- Open mSupply Version: v2.1.-0
- Legacy mSupply Central Server Version: v7-16

- Platform: browser(chrome)

- Database type: sqlite

**Comment by roxy-dao** [comment] 2024-07-24 19:27
Closing as duplicate of #4325

**Closed by roxy-dao** 2024-07-24 19:27 UTC
Labels: bug, enhancement, needs triage, Severity: Low, needs daily triage
