### ISSUE TITLE
Can't type in a date field on mobile 

### ISSUE THREAD

**Issue by DhanyaHerath** [msupply-foundation/open-msupply#2884] opened 2024-02-02 03:28 UTC
## What went wrong? 😲
 
You can't type into a date field while on mobile. Clicking on the field opens up the date selector, and that's the only way you can enter in a date. 

## Expected behaviour 🤔
Would it be possible to have the option to type in a date?

## How to Reproduce 🔨

Steps to reproduce the behaviour:
I think all the date fields behave this way, but here's one example:

1. Create a patient 
2. Try to enter the Date of Birth 
3. See that it opens up a date selector 

## Your environment 🌱

 - Version: 1.6.1
 - Platform:
   - [x] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

**Comment by DhanyaHerath** [comment] 2024-02-06 20:41
Wasn't sure whether this was intended behaviour for mobile or a bug @mark-prins @roxy-dao

**Comment by mark-prins** [comment] 2024-02-06 21:45
Not intended, no. we're using the material UI date picker component and it should work on mobile

**Comment by DhanyaHerath** [comment] 2024-02-06 22:37
Thanks! @mark-prins In that case could we consider doing this as a patch fix for Cooks? It would be nice to help Jess and team out with a fix while in country :)

**Comment by mark-prins** [comment] 2024-02-07 00:04
This is default behaviour of the date picker component - we are using `<DatePicker>` which, according to the [docs](https://mui.com/x/react-date-pickers/date-picker/#available-components) will render the `DesktopDatePicker` or `MobileDatePicker` depending on the device it runs on. The `MobileDatePicker` behaves as you've described, i.e. it only allows entry using the modal picker.

Given that material UI have move UX depth than we do, I'm inclined to take their advice on this and use the standard behaviour. @DhanyaHerath  can I close the issue?

**Comment by CarlosNZ** [comment] 2024-02-07 00:08
This was something @jagoje mentioned to me too. I can't remember specifically, but she said something about it being the particular interface on Mobile was particularly difficult to work with, less so that you couldn't type manually (i.e. if the UI was better, the picker would be adequate). I'd get her to clarify this before closing, I think.

**Comment by clemens-msupply** [comment] 2024-02-08 01:36
In https://docs.google.com/document/d/1UchQFRQwgzdLtsB94uid2XZ-2icsAf6uVNeI1U2vZ5o/edit
Jess also mentioned a timezone issue (?).

> Date defaults to the previous day's date when selecting a DOB in the patient data picker field. E.g. select 26th Jan, system records 25th Jan as date.

Not sure if this is part of this issue? or if there is already an issue for it?

**Comment by DhanyaHerath** [comment] 2024-02-08 01:49
Not part of the issue yet because Jess wanted to check whether it was only on her test server

**Comment by mark-prins** [comment] 2024-02-08 03:20
the DOB date picker issue was an interesting one! 
unrelated to this, I think. This one is about the MobileDatePicker and I think that there's no action required.

**Comment by DhanyaHerath** [comment] 2024-02-08 03:31
Hm yes, thanks @mark-prins if this is default behaviour I think we should defer to Material UI. Interested to hear more about what Carl was mentioning though! 

The DOB date picker...still seems to be happening for them, even outside the test server. Worth another issue? Sounds like a pain

**Comment by jagoje** [comment] 2024-02-08 06:37
> This was something @jagoje mentioned to me too. I can't remember specifically, but she said something about it being the particular interface on Mobile was particularly difficult to work with, less so that you couldn't type manually (i.e. if the UI was better, the picker would be adequate). I'd get her to clarify this before closing, I think.

Howdy all, to wrap up this: 
- When not using the keyboard the not being able to type the DOB in the android app is the expected behaviour sounds good., We are no longer using the keyboard so happy to let this slide, but I would note that IF a keyboard is connected in the future it would be great to be able to type.
- I will say the data picker used in the stock section (for expiry) has been found to be much more intuitive to users as you first select Year, then the picker changes to Month view. The Date picker for the patients DOB field has the user select the day in calendar view, the year from a list and then month using the left right arrows to scroll through the months. The one I have seen difficulty with is the months. Having to tap the arrow to go through the months has been a bit tricky for users, would be easier if they could select the month I think like the year field. 
- Overall i agree this issue is low priority for me. Especially in comparison with the DOB data picker issue (much higher priority for me if possible!)

**Comment by mark-prins** [comment] 2024-02-11 23:05
thanks all, closing this one. can reopen if there are further issue

**Closed by mark-prins** 2024-02-11 23:05 UTC
Labels: bug
