### ISSUE TITLE
show 0 soh in stock detail window

### ISSUE THREAD

**Issue by louisaw123** [msupply-foundation/open-msupply#4332] opened 2024-07-01 10:29 UTC
## Is your feature request related to a problem? Please describe 👀

when soh is 0 should indicate in picture below with the same bar graph and show as soh 0 otherwise there is nothing there and users might not know what is going on esp since it doesn't say anywhere else in that window what soh is

## Describe the solution you'd like 🎁
<img width="1469" alt="Screenshot 2024-07-01 at 10 24 19 PM" src="https://github.com/msupply-foundation/open-msupply/assets/143057869/c2361ce8-3a23-4a9a-a52a-dd23f0828d5b">

**Comment by roxy-dao** [comment] 2024-07-01 10:47
Duplicate of #2780

**Closed by roxy-dao** 2024-07-01 10:47 UTC
Labels: enhancement, needs triage
