### ISSUE TITLE
Add customisable nested breadcrumbs

### ISSUE THREAD

**Issue by fergie-nz** [msupply-foundation/open-msupply#4063] opened 2024-06-06 22:39 UTC
## Is your feature request related to a problem? Please describe 👀

We want to be able to customise nested breadcrumbs values to give users more context of where they are when going through nested pages.

For new Programs route we go to:

Immunization programs page
-> Immunization Program detail page (which includes a list of Vaccine Courses)
    -> Vaccine course detail view

Breadcrumbs look like this:
![Image 07-06-2024 at 10 06](https://github.com/msupply-foundation/open-msupply/assets/90807420/9ff5aa9f-fdc7-411b-bd15-55738970f0d5)

Where 'id' would be a UUID and could be confusing for users.

## Describe the solution you'd like 🎁

Allow breadcrumbs to customise nested values.

### Moneyworks Jobcode 🧰

Could be under CCEIDEV as this is only being used currently in cold chain module.
Or maybe a more generic code?
I am unsure.

**Comment by andreievg** [comment] 2024-06-12 23:18
Triage, adding as nice to have, there are some design discussions about navigation in general, maybe it's fixed then

**Comment by mark-prins** [comment] 2024-06-13 01:43
An example:

<img width="580" alt="image" src="https://github.com/msupply-foundation/open-msupply/assets/9192912/24c93edd-8537-4d74-9c19-28eda6ea3ab5">

A couple of implementation thoughts:
* refactor how the `suffix` / `setSuffix` is working. Expose `urlParts` so that you can specify a part directly and replace `setSuffix` usage with this new approach, using the final index of the breadcrumb. or for a slightly less impact refactor: create a new `setSuffix` in `useBreadcrumbs` which does the `urlParts` manipulation. the `Breadcrumbs` component will need modifying to check the type of each part (not just the suffix, as now)
* implement the ability to provide a mapping function which take an index and provide a value: this can be used to specify both the suffix and other parts of the URL / breadcrumb

**Comment by mark-prins** [comment] 2024-06-16 22:40
For the immediate problem - I would actually use a modal rather than a new page. We don't go down to level 3 if we do that and don't need the breadcrumb change

**Comment by mark-prins** [comment] 2024-06-21 00:38
bit if a duplicate of #2118

**Comment by fergie-nz** [comment] 2024-06-24 00:52
Solving this temporarily by converting to a modal.

Can address breadcrumb issue #2118 at later stage

**Comment by fergie-nz** [comment] 2024-06-24 01:47
Unpacking this a bit more I am realising we already have a create modal for when creating new vaccine courses:

![Image](https://github.com/msupply-foundation/open-msupply/assets/90807420/7ef717c3-ca52-4943-b542-15ea06ddfd3a)

Feels quite clumsy to have two separate modals here with one changing to the other:

![Image](https://github.com/msupply-foundation/open-msupply/assets/90807420/d2929209-433a-405d-bfa3-418a1fcc4824)


So I am wanting to combine both create and edit mutations to use the second modal which would involve updating the insert mutation and getting rid of the current create modal.

I'm realising this is a bit more than I had initially expected and will involve double handling for if and when we want to move back to a page view when breadcrumbs are fixed. 

Curious what you all reckon and if still worth doing?

**Comment by mark-prins** [comment] 2024-06-24 03:58
yep! I think it is - and Mariya has been pushing us to implement this sort of pattern too. It's a bit clunky entering a name in one modal, then navigating to somewhere else (another page, another modal) to enter the rest of the deets

**Comment by fergie-nz** [comment] 2024-06-24 04:12
OK great I will consolidate the modals :)

**Comment by fergie-nz** [comment] 2024-06-24 04:14
Also had a little look at pulling out breadcrumbs logic into the component to overwrite url parts:
https://github.com/msupply-foundation/open-msupply/compare/release-v2.1.0...4063-play-with-breadcrumbs

**Closed** 2024-07-02 04:41 UTC
Labels: enhancement, Priority: Nice to Have, Team Piwakawaka, feature: GAPS

**Comment by marthakeezy** [comment] 2024-07-05 02:15
Tested in V2.1.0-RC6, under: 

- Programs -> Immunizations
- Cold chain -> Equipment 
- Inventory -> View Stock

And all breadcrumbs are showing as expected :) Build test passed! ✅
