### ISSUE TITLE
After merging items, should oms retain previous merged item name on invoices, requisitions etc.?

### ISSUE THREAD

**Issue by nisha-dangol** [msupply-foundation/open-msupply#3556] opened 2024-04-05 09:07 UTC
## What went wrong? 😲
 
From [here!](https://github.com/msupply-foundation/open-msupply/issues/2450#issuecomment-2031528760) 

After merging items, should oms retain previous merged (deleted) item's names (obviously pointing to kept item afterwards) on invoice lines?

## Expected behaviour 🤔
please vote/decide:
Either, 1: retain the merged name/item for the sake of record-keeping, but point it to the kept name/item
Or, 2: once merged, no more retaining of old name/item at all; replace merged name/item with kept ones

## How to Reproduce 🔨
Steps to reproduce the behaviour:

1. Create an outbound shipment from one oms-store to another oms-store with two items
2. Sync and received the inbound and stock-in and sync
3. On desktop cloud, merge those two items and sync
4. In oms-stores, revisit the shipments: the merged-items are replaced by the kept-item in both inbound & outbound

## Your environment 🌱

- Open mSupply Version: v1.7.0
- Legacy mSupply Central Server Version: v714-dev5

- Platform: server exe, browser(chrome)

- Database type: sqlite

**Comment by Chris-Petty** [comment] 2024-04-11 00:31
I've removed `name` table from this issue because that is very different (name's name should always update after merge in all contexts as far as I'm aware). My understanding for years is the expected behaviour for item name is that previous item names are maintained in invoices - that's what `invoice_line.item_name` and `invoice_line.item_code` exist in both OG and OMS. OG also has `requisition_line.itemName`, but it is not consistently used as far as I've seen at a glance. All contexts where there is a relation to item name should be reviewed and the status of the parent record considered. Really needs to be decided by product owners of old and new: 

@richardmoizeau @craigdrown can one or both of you please clarify desired behaviour when item names in various contexts should be updated when a merge occurs:

- new prescription
- confirmed prescription (note - I believe labels may already be printed at this stage)
- finalised prescription
- suggested customer invoice (/supplier credit/inventory reduction)
- confirmed customer invoice
- finalised customer invoice
- suggested supplier invoice (/customer credit/inventory addition)
- confirmed supplier invoice
- finalised supplier invoice
- Stock takes?
- Requisitions?
- Purchase Orders?
- Goods Receipts?
- Tenders?

**Comment by craigdrown** [comment] 2024-04-11 02:18
The idea of a denormalised field (like invoice_line.item_name) is to retain the value that was actually used at that time - this is legally required for prescriptions- not just for merges, but for instance if you changed the strength of the item after issuing and the patient is dead - did you give them the 250mg or the 500mg? - needs to not be updated. For non-finalised invoices etc the user can update by deleting the line and adding again.

**Comment by Chris-Petty** [comment] 2024-04-15 22:40
This is working as intended then if the item name from before merge is kept on invoice/prescription lines, I'll close this unless that is not what is happening @nisha-dangol ?

**Comment by nisha-dangol** [comment] 2024-04-16 07:51
> This is working as intended then if the item name from before merge is kept on invoice/prescription lines, I'll close this unless that is not what is happening @nisha-dangol ?

In that case, I'm definitely re-opening this issue, since the merged items are gone (only kept items are showing)

**Comment by ujwalSussol** [comment] 2024-04-16 07:52
> The idea of a denormalised field (like invoice_line.item_name) is to retain the value that was actually used at that time - this is legally required for prescriptions- not just for merges, but for instance if you changed the strength of the item after issuing and the patient is dead - did you give them the 250mg or the 500mg? - needs to not be updated. For non-finalised invoices etc the user can update by deleting the line and adding again.

@craigdrown  :  We had a debate regarding this on our standup --- I agree, from an accounting point of view >> we should not be updating the text for old  `Item_name`

**Comment by Chris-Petty** [comment] 2024-04-17 02:48
> > This is working as intended then if the item name from before merge is kept on invoice/prescription lines, I'll close this unless that is not what is happening @nisha-dangol ?
> 
> In that case, I'm definitely re-opening this issue, since the merged items are gone (only kept items are showing)

You're describing a new issue which you've opened as #14606. This one is closed - old invoices should show the old item names used at the time invoice line was added.

**Comment by nisha-dangol** [comment] 2024-04-18 05:29
Reopening. From here: https://github.com/msupply-foundation/msupply/issues/14606#issuecomment-2060939697 : In oms v1.7.0, I still see that merged-items are not retained in shipments as well.

**Comment by Chris-Petty** [comment] 2024-04-18 21:15
@craigdrown bit of a funky edge case - if an inbound shipment is generated after the merge, should the item name be copied from the outbound shipment of the supplier? I.e. I presume inbound and outbound shipment documents should match? Though if it's `500mg` merged -> `250mg` users reviewing inbound shipment will still see `500mg` and may remove that line and add a line for `250mg` anyway...

**Comment by craigdrown** [comment] 2024-04-18 22:49
@Chris-Petty I think anything incoming that is not finalised could be updated? 
I see PO lines have item name but GR lines don't. 
I think updating POs that are not finalised has some risk, but so does not updating them, so better to do it.

**Comment by Chris-Petty** [comment] 2024-04-18 23:46
@craigdrown starts getting a bit chaotic sorry - confirmed PO lines that don't relate to a finalised quote line -> finalised tender line or is that OK to mismatch?

**Comment by craigdrown** [comment] 2024-04-19 02:44
POs are impt docs - legal problems changing them after we sent it to the supplier. Happy to discuss in person. Not sure what current behaviour is?

**Closed** 2024-04-22 20:01 UTC
Labels: bug, feature: merging, Team Tauhou, Severity: High

**Comment by Chris-Petty** [comment] 2024-04-23 21:54
> POs & Tenders are impt docs - legal problems changing them after we sent it to the supplier. Happy to discuss in person. Not sure what current behaviour is?

Item line field:

- PO line: yes (UI appears to use it too)
- Tender line: yes (UI appears to use it too)
- Quote line: no
